1. Import the necessary libraries

In [77]:
import numpy as np
import pandas as pd

2. Import the dataset chipotle.tsv

3. Assign it to a variable called chipo

In [81]:
chipo = pd.read_csv('chipotle.tsv', sep='\t')

4. See the first 10 entries

In [84]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

5. What is the number of observations in the dataset?

In [87]:
chipo.shape

(4622, 5)

In [89]:
chipo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

6. What is the number of columns in the dataset?

In [92]:
chipo.shape[1]

5

7. Print the name of all the columns

In [95]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

8. How is the dataset indexed?

In [98]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

9. Which was the most-ordered item?

In [101]:
most_order = chipo.groupby('item_name').agg({'quantity': 'sum'})
most_order

                                       quantity
item_name
6 Pack Soft Drink                            55
Barbacoa Bowl                                66
Barbacoa Burrito                             91
Barbacoa Crispy Tacos                        12
Barbacoa Salad Bowl                          10
Barbacoa Soft Tacos                          25
Bottled Water                               211
Bowl                                          4
Burrito                                       6
Canned Soda                                 126
Canned Soft Drink                           351
Carnitas Bowl                                71
Carnitas Burrito                             60
Carnitas Crispy Tacos                         8
Carnitas Salad                                1
Carnitas Salad Bowl                           6
Carnitas Soft Tacos                          40
Chicken Bowl                                761
Chicken Burrito                             591
Chicken Crispy Tacos                         50
Chicken Salad                                 9
Chicken Salad Bowl                          123
Chicken Soft Tacos                          120
Chips                                       230
Chips and Fresh Tomato Salsa                130
Chips and Guacamole                         506
Chips and Mild Fresh Tomato Salsa             1
Chips and Roasted Chili Corn Salsa           23
Chips and Roasted Chili-Corn Salsa           18
Chips and Tomatillo Green Chili Salsa        45
Chips and Tomatillo Red Chili Salsa          50
Chips and Tomatillo-Green Chili Salsa        33
Chips and Tomatillo-Red Chili Salsa          25
Crispy Tacos                                  2
Izze                                         20
Nantucket Nectar                             29
Salad                                         2
Side of Chips                               110
Steak Bowl                                  221
Steak Burrito                               386
Steak Crispy Tacos                           36
Steak Salad                                   4
Steak Salad Bowl                             31
Steak Soft Tacos                             56
Veggie Bowl                                  87
Veggie Burrito                               97
Veggie Crispy Tacos                           1
Veggie Salad                                  6
Veggie Salad Bowl                            18
Veggie Soft Tacos                             8

In [103]:
most_order.sort_values('quantity', ascending=False).head(1)

              quantity
item_name
Chicken Bowl       761

11. What was the most ordered item in the choice_description column?

In [109]:
most_order2 = chipo.groupby('choice_description').agg({'order_id': 'sum', 'quantity': 'sum'})

In [111]:
most_order2

                                                    order_id  quantity
choice_description
[Adobo-Marinated and Grilled Chicken, Pinto Bea...       214         1
[Adobo-Marinated and Grilled Chicken, [Sour Cre...       279         1
[Adobo-Marinated and Grilled Chicken]                    217         1
[Adobo-Marinated and Grilled Steak, [Sour Cream...       279         1
[Adobo-Marinated and Grilled Steak]                      217         1
...                                                      ...       ...
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      2576         2
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      1215         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...        51         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...        51         1
[[Tomatillo-Red Chili Salsa (Hot), Tomatillo-Gr...      1299         1

[1043 rows x 2 columns]

12. How many items were orderd in total?

In [114]:
most_order2['quantity'].sum()

3590

13. Turn the item price into a float

a. Check the item price type

In [118]:
chipo['item_price'].dtype

dtype('O')

b. Create a lambda function and change the type of item price

In [121]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]))

In [123]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [125]:
chipo['item_price']

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

c. Check the item price type

In [128]:
chipo['item_price'].dtype

dtype('float64')

14. How much was the revenue for the period in the dataset?

In [173]:
revenue = sum(chipo['item_price'] * chipo['quantity'])

In [175]:
revenue

39237.02

15. How many orders were made in the period?

In [136]:
chipo['order_id'].max()

1834

16. What is the average revenue amount per order?

In [195]:
chipo.groupby('order_id')['item_price'].sum().sort_values(ascending=False).mean()

18.811428571428575

In [191]:
chipo[chipo['order_id']==926]

,order_id,quantity,item_name,choice_description,item_price,revenue
2304,926,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Lettuce]]",9.25,9.25
2305,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
2306,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
2307,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
2308,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Lettu...",9.25,9.25
2309,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75
2310,926,1,Steak Burrito,"[Roasted Chili Corn Salsa, [Rice, Cheese, Sour...",9.25,9.25
2311,926,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75,8.75
2312,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce]]",8.75,8.75
2313,926,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...",8.75,8.75
2314,926,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream]]",8.75,8.75
2315,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25,9.25
2316,926,1,Chicken Burrito,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75,8.75
2317,926,1,Steak Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",9.25,9.25
2318,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
2319,926,1,Steak Bowl,"[Fresh Tomato Salsa, [Rice, Cheese]]",9.25,9.25
2320,926,1,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]",8.75,8.75
2321,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Pinto Beans,...",8.75,8.75
2322,926,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese]]",8.75,8.75
2323,926,1,Barbacoa Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",9.25,9.25
2324,926,1,Chicken Burrito,"[Tomatillo Red Chili Salsa, [Rice, Cheese, Sou...",8.75,8.75
2325,926,1,Steak Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",9.25,9.25
2326,926,1,Veggie Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75,8.75

In [142]:
chipo['revenue'] = chipo['quantity'] *  chipo['item_price']

In [144]:
chipo

,order_id,quantity,item_name,choice_description,item_price,revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [161]:
chipo.head()

,order_id,quantity,item_name,choice_description,item_price,revenue
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,33.96

quantity       2.711014
item_price    18.811429
revenue       21.394231
dtype: float64

21.394231188658654

17. How many different items are sold?

In [235]:
chipo['item_name'].nunique()

50

In [237]:
chipo['item_name'].value_counts().count()

50

18. How many products cost more than $10.00?

In [242]:
cost = chipo[chipo['item_price'] > 10]
cost['item_name'].nunique()

31

31

19. What is the price of each item?

In [276]:
chipo[['item_name','item_price']].groupby('item_name').head()

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
3363                          Chicken Salad        8.49
3471                           Veggie Salad        8.49
3502                            Steak Salad        8.69
3749                    Carnitas Salad Bowl       11.89
3750                         Carnitas Salad        8.99

[228 rows x 2 columns]

In [280]:
chipo[['item_name','item_price']].groupby('item_name').head().shape

(228, 2)

(50, 1)

                                       item_price
item_name
6 Pack Soft Drink                           12.98
Barbacoa Bowl                               11.75
Barbacoa Burrito                            11.75
Barbacoa Crispy Tacos                       18.50
Barbacoa Salad Bowl                         11.89
Barbacoa Soft Tacos                         11.75
Bottled Water                               15.00
Bowl                                        22.20
Burrito                                      7.40
Canned Soda                                  4.36
Canned Soft Drink                            5.00
Carnitas Bowl                               35.25
Carnitas Burrito                            18.50
Carnitas Crispy Tacos                       17.98
Carnitas Salad                               8.99
Carnitas Salad Bowl                         11.89
Carnitas Soft Tacos                         11.75
Chicken Bowl                                32.94
Chicken Burrito                             35.00
Chicken Crispy Tacos                        17.50
Chicken Salad                               10.98
Chicken Salad Bowl                          22.50
Chicken Soft Tacos                          21.96
Chips                                        6.45
Chips and Fresh Tomato Salsa                44.25
Chips and Guacamole                         17.80
Chips and Mild Fresh Tomato Salsa            3.00
Chips and Roasted Chili Corn Salsa           5.90
Chips and Roasted Chili-Corn Salsa           2.39
Chips and Tomatillo Green Chili Salsa        5.90
Chips and Tomatillo Red Chili Salsa          5.90
Chips and Tomatillo-Green Chili Salsa        4.78
Chips and Tomatillo-Red Chili Salsa          7.17
Crispy Tacos                                 7.40
Izze                                         3.39
Nantucket Nectar                             6.78
Salad                                        7.40
Side of Chips                               13.52
Steak Bowl                                  26.07
Steak Burrito                               27.75
Steak Crispy Tacos                          17.98
Steak Salad                                  8.99
Steak Salad Bowl                            23.78
Steak Soft Tacos                            18.50
Veggie Bowl                                 16.98
Veggie Burrito                              33.75
Veggie Crispy Tacos                          8.49
Veggie Salad                                 8.49
Veggie Salad Bowl                           11.25
Veggie Soft Tacos                           16.98

20. Sort by the name of the item

3389    6 Pack Soft Drink
341     6 Pack Soft Drink
1849    6 Pack Soft Drink
1860    6 Pack Soft Drink
2713    6 Pack Soft Drink
              ...
2384    Veggie Soft Tacos
781     Veggie Soft Tacos
2851    Veggie Soft Tacos
1699    Veggie Soft Tacos
1395    Veggie Soft Tacos
Name: item_name, Length: 4622, dtype: object

21. What was the quantity of the most expensive item ordered?

In [282]:
chipo.sort_values('quantity', ascending=False).head(1)

,order_id,quantity,item_name,choice_description,item_price,revenue
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,663.75

,order_id,quantity,item_name,choice_description,item_price,revenue
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,663.75

22. How many times was a Veggie Salad Bowl ordered?

In [298]:
count = chipo[chipo['item_name'] == 'Veggie Salad Bowl']
count['quantity'].count()

18

23. How many times did someone order more than one Canned Soda?

In [324]:
chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)].count()

order_id              20
quantity              20
item_name             20
choice_description    20
item_price            20
revenue               20
dtype: int64

order_id              20
quantity              20
item_name             20
choice_description    20
item_price            20
revenue               20
dtype: int64