#### 1 Создание фрейма данных

In [1]:
import numpy as np
import pandas as pd

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\robhul\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\robhul\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\robhul\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\robhul\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\robhul\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\robhul\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

Ядром pandas являются две структуры данных, в которых происходят все операции: Series и DataFrames.

Series — это объект библиотеки pandas, спроектированный для представления одномерных структур данных, похожих на массивы, но с дополнительными возможностями. Его структура проста, ведь он состоит из двух связанных между собой массивов. Основной содержит данные (данные любого типа NumPy), а в дополнительном, index, хранятся метки.

#### Создание объекта Series

Для создания объекта Series необходимо вызвать конструктор Series() и передать в качестве аргумента массив, содержащий значения, которые необходимо включить.

In [42]:
letters = ['a', 'b', 'c']
numbers = [1, 2, 3]
arr = np.array(numbers)
dict = {'a':1, 'b':2, 'c':3}

In [44]:
pd.Series(numbers)

0    1
1    2
2    3
dtype: int64

In [46]:
pd.Series(data=numbers, index=letters)

a    1
b    2
c    3
dtype: int64

In [48]:
pd.Series(numbers, letters)

a    1
b    2
c    3
dtype: int64

In [50]:
pd.Series(dict)

a    1
b    2
c    3
dtype: int64

Если объект Series — аналог одномерного массива с гибкими индексами, объект DataFrame — аналог двумерного массива с гибкими индексами строк и гибкими именами столбцов. Аналогично тому, что двумерный массив можно рассматривать как упорядоченную последовательность выровненных столбцов, объект DataFrame можно рассматривать как упорядоченную последовательность выровненных объектов Series. Под «выровненными» имеется в виду то, что они используют один и тот же индекс.

#### Создание объекта DataFrame

In [54]:
df = pd.DataFrame(np.random.randn(4, 5), [1, 2, 3, 4], ['red', 'orange', 'yellow', 'green', 'blue'])

In [56]:
df

        red    orange    yellow     green      blue
1  0.700591 -1.424615  0.637510  0.549817 -0.306042
2 -0.810816  0.720195 -0.321762  2.523070  0.762314
3  1.035020 -0.161850 -0.452054  0.137250  0.527517
4  1.085780  1.216484 -1.504190 -0.174056  1.370243

In [58]:
df.columns

Index(['red', 'orange', 'yellow', 'green', 'blue'], dtype='object')

In [60]:
df.index

Index([1, 2, 3, 4], dtype='int64')

In [62]:
df['orange']

1   -1.424615
2    0.720195
3   -0.161850
4    1.216484
Name: orange, dtype: float64

In [64]:
type(df)

pandas.core.frame.DataFrame

In [66]:
type(df['orange'])

pandas.core.series.Series

In [68]:
df[['yellow', 'blue']]

     yellow      blue
1  0.637510 -0.306042
2 -0.321762  0.762314
3 -0.452054  0.527517
4 -1.504190  1.370243

In [70]:
df['indigo'] = df['blue']

In [72]:
df

        red    orange    yellow     green      blue    indigo
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.306042
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314
3  1.035020 -0.161850 -0.452054  0.137250  0.527517  0.527517
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243

In [74]:
df['violet'] = df['blue'] + df['indigo']

In [76]:
df

        red    orange    yellow     green      blue    indigo    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
3  1.035020 -0.161850 -0.452054  0.137250  0.527517  0.527517  1.055034
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

#### Навигация по фреймам данных

Для выбора одной или нескольких строк либо значений использовать методы lос или iloc. Все строки во фрейме данных pandas имеют уникальное индексное значение. По умолчанию этот индекс является целым числом, указывающим на положение строки во фрейме данных; однако это не обязательно. Метод lос полезен, когда индекс фрейма является меткой (например, строковым значением). Метод iloc работает, отыскивая позицию во фрейме данных (по номеру индекса).

In [80]:
df.loc[2]

red      -0.810816
orange    0.720195
yellow   -0.321762
green     2.523070
blue      0.762314
indigo    0.762314
violet    1.524628
Name: 2, dtype: float64

In [82]:
df.iloc[1]

red      -0.810816
orange    0.720195
yellow   -0.321762
green     2.523070
blue      0.762314
indigo    0.762314
violet    1.524628
Name: 2, dtype: float64

In [84]:
df.iloc[2] = df.iloc[1]

In [86]:
df

        red    orange    yellow     green      blue    indigo    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
3 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

In [88]:
df.loc[3, 'orange']

0.7201953350384038

In [90]:
df.iloc[2, 1]

0.7201953350384038

In [92]:
df.loc[[1,3], ['blue', 'violet']]

       blue    violet
1 -0.306042 -0.612084
3  0.762314  1.524628

#### Выбор строк на основе условных конструкций

In [95]:
df[df > 0]

        red    orange   yellow     green      blue    indigo    violet
1  0.700591       NaN  0.63751  0.549817       NaN       NaN       NaN
2       NaN  0.720195      NaN  2.523070  0.762314  0.762314  1.524628
3       NaN  0.720195      NaN  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484      NaN       NaN  1.370243  1.370243  2.740487

In [97]:
df['yellow'] > 0

1     True
2    False
3    False
4    False
Name: yellow, dtype: bool

In [99]:
df[df['yellow']<0]

        red    orange    yellow     green      blue    indigo    violet
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
3 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

In [101]:
df[df['yellow']<0]['green']

2    2.523070
3    2.523070
4   -0.174056
Name: green, dtype: float64

In [103]:
df[df['yellow']<0][['green','blue']]

      green      blue
2  2.523070  0.762314
3  2.523070  0.762314
4 -0.174056  1.370243

In [104]:
df[(df['blue']>0) & (df['yellow']<0)]

        red    orange    yellow     green      blue    indigo    violet
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
3 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

In [107]:
df[(df['blue']>0) | (df['yellow']<0)]

        red    orange    yellow     green      blue    indigo    violet
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
3 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

#### Удаление строк

In [110]:
# удаление строк axis = 0 столбец axis = 1  inplace=False без удаления из датафрейма, inplace=True с удалением
df.drop(3)

        red    orange    yellow     green      blue    indigo    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

In [112]:
df

        red    orange    yellow     green      blue    indigo    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
3 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

In [114]:
df.drop(3, inplace = True)

In [116]:
df

        red    orange    yellow     green      blue    indigo    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  1.370243  2.740487

In [118]:
df.drop('indigo', axis = 1, inplace = True)

In [120]:
df

        red    orange    yellow     green      blue    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628
4  1.085780  1.216484 -1.504190 -0.174056  1.370243  2.740487

####  Удаление повторяющихся строк

Метод drop_duplicates() по умолчанию отбрасывает только те строки, которые идеально совпадают по всем столбцам.

In [124]:
df.iloc[2] = df.iloc[1]

In [126]:
df

        red    orange    yellow     green      blue    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628
4 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628

In [128]:
# Удалить дубликаты, показать строки  
df.drop_duplicates().head()

        red    orange    yellow     green      blue    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628

In [130]:
df

        red    orange    yellow     green      blue    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628
4 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628

In [132]:
df = df.drop_duplicates().head()

In [134]:
df

        red    orange    yellow     green      blue    violet
1  0.700591 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628

Чтобы выполнить проверку на наличие повторяющихся строк, нередко требуется рассмотреть только подмножество столбцов. Это можно сделать с помощью параметра subset. Метод drop_duplicates по умолчанию сохраняет первое появление повторяющейся строки и удаляет остальные

In [137]:
df.loc[1,'red'] = df.loc[2,'red']

In [139]:
df

        red    orange    yellow     green      blue    violet
1 -0.810816 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.810816  0.720195 -0.321762  2.523070  0.762314  1.524628

In [141]:
df.drop_duplicates(subset=['red'])

        red    orange   yellow     green      blue    violet
1 -0.810816 -1.424615  0.63751  0.549817 -0.306042 -0.612084

#### Замена значений

In [143]:
df['orange'].mean()

-0.35221003459956

In [154]:
# Заменить значения 
df['red'].replace(df.loc[1, 'red'],df['orange'].mean(), inplace=True)

C:\Users\robhul\AppData\Local\Temp\ipykernel_9800\3680650645.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['red'].replace(df.loc[1, 'red'],df['orange'].mean(), inplace=True)

In [155]:
df

       red    orange    yellow     green      blue    violet
1 -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084
2 -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628

#### Работа с индексами

reset_index() — это метод сброса индекса фрейма данных. Метод .reset_index () задает список целых чисел от 0 до длины данных в качестве индекса.

In [160]:
df.reset_index()
# inplace = True

   index      red    orange    yellow     green      blue    violet
0      1 -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084
1      2 -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628

In [162]:
z1 = [2, 3]
df['Z1'] = z1

In [164]:
df

       red    orange    yellow     green      blue    violet  Z1
1 -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084   2
2 -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628   3

In [166]:
df.set_index('Z1')

        red    orange    yellow     green      blue    violet
Z1
2  -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084
3  -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628

#### Переименование столбцов

In [169]:
# Переименовать столбец, показать две строки
df.rename(columns={'red': 'Red'}).head()

       Red    orange    yellow     green      blue    violet  Z1
1 -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084   2
2 -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628   3

In [171]:
df

       red    orange    yellow     green      blue    violet  Z1
1 -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084   2
2 -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628   3

In [173]:
df.rename(columns={'red': 'Red'}, inplace=True)

In [175]:
df

       Red    orange    yellow     green      blue    violet  Z1
1 -0.35221 -1.424615  0.637510  0.549817 -0.306042 -0.612084   2
2 -0.35221  0.720195 -0.321762  2.523070  0.762314  1.524628   3