In [1]:
import pandas as pd
import numpy as np

#### Вычисление статистических показателей

In [2]:
df = pd.DataFrame(np.random.randint(1, 101, 35).reshape(7, 5), ['a', 'b', 'c', 'd', 'e', 'f', 'g'], 
                  ['France', 'Spain', 'Italy', 'Germany', 'Great Britain'])

In [3]:
df

   France  Spain  Italy  Germany  Great Britain
a      62     52     68       33             57
b      41     53     41       48             85
c      98     53     34       65             85
d      84     56     62       71             43
e      65     22      4       22             27
f      12     20     85       68             33
g      69      2     35       57             16

In [5]:
df['France'].max()

98

In [6]:
df['France'].min()

12

In [7]:
df['France'].sum()

431

In [8]:
df['France'].mean()

61.57142857142857

In [9]:
df['France'].count()

7

In [10]:
df.max()

France           98
Spain            56
Italy            85
Germany          71
Great Britain    85
dtype: int32

In [11]:
df.describe()

          France      Spain      Italy    Germany  Great Britain
count   7.000000   7.000000   7.000000   7.000000       7.000000
mean   61.571429  36.857143  47.000000  52.000000      49.428571
std    28.218535  21.744184  26.795522  18.654758      27.446051
min    12.000000   2.000000   4.000000  22.000000      16.000000
25%    51.500000  21.000000  34.500000  40.500000      30.000000
50%    65.000000  52.000000  41.000000  57.000000      43.000000
75%    76.500000  53.000000  65.000000  66.500000      71.000000
max    98.000000  56.000000  85.000000  71.000000      85.000000

In [12]:
df.describe().T

               count       mean        std   min   25%   50%   75%   max
France           7.0  61.571429  28.218535  12.0  51.5  65.0  76.5  98.0
Spain            7.0  36.857143  21.744184   2.0  21.0  52.0  53.0  56.0
Italy            7.0  47.000000  26.795522   4.0  34.5  41.0  65.0  85.0
Germany          7.0  52.000000  18.654758  22.0  40.5  57.0  66.5  71.0
Great Britain    7.0  49.428571  27.446051  16.0  30.0  43.0  71.0  85.0

#### Нахождение уникальных значений

In [13]:
df.loc['a','France'] = 99

In [14]:
df

   France  Spain  Italy  Germany  Great Britain
a      99     52     68       33             57
b      41     53     41       48             85
c      98     53     34       65             85
d      84     56     62       71             43
e      65     22      4       22             27
f      12     20     85       68             33
g      69      2     35       57             16

In [15]:
df['France'].unique()

array([99, 41, 98, 84, 65, 12, 69])

In [16]:
# Количество уникальных значений
df['France'].nunique()

7

In [17]:
# Показать количества появлений 
df['France'].value_counts()

99    1
41    1
98    1
84    1
65    1
12    1
69    1
Name: France, dtype: int64

#### Отбор пропущенных значений

В библиотеке pandas для обозначения пропущенных значений используется значение NaN библиотеки NumPy (от англ. Not a Number — не число).

In [18]:
df.loc['a', 'France'] = np.NaN

In [19]:
df

   France  Spain  Italy  Germany  Great Britain
a     NaN     52     68       33             57
b    41.0     53     41       48             85
c    98.0     53     34       65             85
d    84.0     56     62       71             43
e    65.0     22      4       22             27
f    12.0     20     85       68             33
g    69.0      2     35       57             16

In [20]:
# Выбрать пропущенные значения
df[df['France'].isnull()].head()

   France  Spain  Italy  Germany  Great Britain
a     NaN     52     68       33             57

In [21]:
df.dropna()

   France  Spain  Italy  Germany  Great Britain
b    41.0     53     41       48             85
c    98.0     53     34       65             85
d    84.0     56     62       71             43
e    65.0     22      4       22             27
f    12.0     20     85       68             33
g    69.0      2     35       57             16

In [22]:
df.dropna(axis=1)

   Spain  Italy  Germany  Great Britain
a     52     68       33             57
b     53     41       48             85
c     53     34       65             85
d     56     62       71             43
e     22      4       22             27
f     20     85       68             33
g      2     35       57             16

In [23]:
df.fillna(value='Something')

      France  Spain  Italy  Germany  Great Britain
a  Something     52     68       33             57
b       41.0     53     41       48             85
c       98.0     53     34       65             85
d       84.0     56     62       71             43
e       65.0     22      4       22             27
f       12.0     20     85       68             33
g       69.0      2     35       57             16

In [24]:
df['France'].fillna(value=df['France'].mean())

a    61.5
b    41.0
c    98.0
d    84.0
e    65.0
f    12.0
g    69.0
Name: France, dtype: float64

In [25]:
df

   France  Spain  Italy  Germany  Great Britain
a     NaN     52     68       33             57
b    41.0     53     41       48             85
c    98.0     53     34       65             85
d    84.0     56     62       71             43
e    65.0     22      4       22             27
f    12.0     20     85       68             33
g    69.0      2     35       57             16

####  Группирование строк по значениям

In [26]:
dict = {'Company':['COMP1', 'COMP1', 'COMP2', 'COMP2', 'COMP3', 'COMP3'], 'Month':['JAN', 'FEB', 'MAR', 'APR', 'May','JUN'], 
       'Salary':[2000, 1500, 3000, 5000, 2500, 3500]}

In [27]:
df = pd.DataFrame(dict)

In [28]:
df

  Company Month  Salary
0   COMP1   JAN    2000
1   COMP1   FEB    1500
2   COMP2   MAR    3000
3   COMP2   APR    5000
4   COMP3   May    2500
5   COMP3   JUN    3500

In [29]:
df.groupby('Company').agg({'Salary': ['sum'], 'Month':['count']})

        Salary Month
           sum count
Company
COMP1     3500     2
COMP2     8000     2
COMP3     6000     2

In [30]:
df.groupby(by='Company').count()

         Month  Salary
Company
COMP1        2       2
COMP2        2       2
COMP3        2       2

In [31]:
groupby_comp = df.groupby('Company')

In [32]:
groupby_comp.count()

         Month  Salary
Company
COMP1        2       2
COMP2        2       2
COMP3        2       2

In [34]:
groupby_comp.sum()

C:\Users\МОиБД\AppData\Local\Temp\ipykernel_16960\802191496.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupby_comp.sum()

         Salary
Company
COMP1      3500
COMP2      8000
COMP3      6000

In [35]:
groupby_comp['Salary'].sum()

Company
COMP1    3500
COMP2    8000
COMP3    6000
Name: Salary, dtype: int64

In [36]:
groupby_comp.sum().loc['COMP3']

C:\Users\МОиБД\AppData\Local\Temp\ipykernel_16960\2850394201.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupby_comp.sum().loc['COMP3']

Salary    6000
Name: COMP3, dtype: int64

In [37]:
groupby_comp.count()

         Month  Salary
Company
COMP1        2       2
COMP2        2       2
COMP3        2       2

In [38]:
groupby_comp.max()

        Month  Salary
Company
COMP1     JAN    2000
COMP2     MAR    5000
COMP3     May    3500

In [39]:
groupby_comp.min()

        Month  Salary
Company
COMP1     FEB    1500
COMP2     APR    3000
COMP3     JUN    2500

In [40]:
df.groupby('Company').describe()

        Salary
         count    mean          std     min     25%     50%     75%     max
Company
COMP1      2.0  1750.0   353.553391  1500.0  1625.0  1750.0  1875.0  2000.0
COMP2      2.0  4000.0  1414.213562  3000.0  3500.0  4000.0  4500.0  5000.0
COMP3      2.0  3000.0   707.106781  2500.0  2750.0  3000.0  3250.0  3500.0

In [41]:
comp3 = df.groupby('Company').describe().transpose()['COMP3']

In [42]:
comp3

Salary  count       2.000000
        mean     3000.000000
        std       707.106781
        min      2500.000000
        25%      2750.000000
        50%      3000.000000
        75%      3250.000000
        max      3500.000000
Name: COMP3, dtype: float64

#### Обход столбца в цикле

In [43]:
for x in df['Company'].loc[:2]:
    print(x)

COMP1
COMP1
COMP2

In [44]:
df['Company'].loc[:2]

0    COMP1
1    COMP1
2    COMP2
Name: Company, dtype: object

#### Применение функции ко всем элементам в столбце

Для применения встроенной или заданной пользователем функции к каждому элементу в столбце использовать метод apply.

In [45]:
def times3(x):
    return x * 3

In [46]:
df['Salary'].apply(times3)

0     6000
1     4500
2     9000
3    15000
4     7500
5    10500
Name: Salary, dtype: int64

In [47]:
df['Salary'].apply(times3).sum()

52500

In [48]:
df['Salary'].apply(lambda x: x * 3)

0     6000
1     4500
2     9000
3    15000
4     7500
5    10500
Name: Salary, dtype: int64

In [49]:
# Сгруппировать строки, применить функцию к группам 
df.groupby('Company').apply(lambda x : x.count())

         Company  Month  Salary
Company
COMP1          2      2       2
COMP2          2      2       2
COMP3          2      2       2

In [50]:
df.groupby('Company')[['Month', 'Salary']].apply(lambda x : x.count())

         Month  Salary
Company
COMP1        2       2
COMP2        2       2
COMP3        2       2

#### Конкатенация фреймов данныx

In [51]:
# Создать фрейм данных
data_a = {'id': ['1', '2', '3'], 'first': ['Alex', 'Amy', 'Allen'], 'last': ['Anderson', 'Ackerman', 'Ali']} 
df_a = pd.DataFrame(data_a, columns = ['id', 'first', 'last'])

In [52]:
# Создать фрейм данных
data_b = {'id': ['4', '5', '6'], 'first': ['Billy', 'Brian', 'Bran'], 'last': ['Bonder', 'Black', 'Balwner']} 
df_b = pd.DataFrame(data_b, columns = ['id', 'first', 'last'])

In [53]:
df_a

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali

In [54]:
df_b

  id  first     last
0  4  Billy   Bonder
1  5  Brian    Black
2  6   Bran  Balwner

In [55]:
# Конкатенировать фреймы данных по строкам 
pd.concat([df_a, df_b], axis=0)

  id  first      last
0  1   Alex  Anderson
1  2    Amy  Ackerman
2  3  Allen       Ali
0  4  Billy    Bonder
1  5  Brian     Black
2  6   Bran   Balwner

In [56]:
# Конкатенировать фреймы данных по столбцам 
pd.concat([df_a, df_b], axis=1)

  id  first      last id  first     last
0  1   Alex  Anderson  4  Billy   Bonder
1  2    Amy  Ackerman  5  Brian    Black
2  3  Allen       Ali  6   Bran  Balwner

####  Слияние фреймов данных

Для того чтобы применить внутреннее соединение, использовать метод merge с параметром on, задающим столбец, по которому происходит слияние

In [57]:
# Создать фрейм данных
employee_data = {'employee_id': ['1', ' 2', '3', '4'], 'name': ['Amy Jones', 'Allen Keys', 'Alice Bees','Tim Horton']}
dataframe_employees = pd.DataFrame(employee_data, columns = ['employee_id', 'name'])

In [58]:
dataframe_employees

  employee_id        name
0           1   Amy Jones
1           2  Allen Keys
2           3  Alice Bees
3           4  Tim Horton

In [59]:
# Создать фрейм данных
sales_data = {'employee_id': ['3', '4', '5', '6'], 'total_sales':[23456, 2512, 2345, 1455]}
dataframe_sales = pd.DataFrame(sales_data, columns = ['employee_id','total_sales'])

In [123]:
dataframe_sales

  employee_id  total_sales
0           3        23456
1           4         2512
2           5         2345
3           6         1455

In [60]:
# Выполнить слияние фреймов данных
pd.merge(dataframe_employees, dataframe_sales, on='employee_id')

  employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

Метод merge по умолчанию выполняет операцию внутреннего соединения. Если необходимо сделать внешнее соединение, можно указать это при помощи параметра how

In [109]:
# Выполнить слияние фреймов данных 
pd.merge(dataframe_employees, dataframe_sales, on='employee_id', how='outer')

  employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0
4           5         NaN       2345.0
5           6         NaN       1455.0

Этот же параметр можно использовать для указания левого и правого соединений

In [110]:
# Выполнить слияние фреймов данных 
pd.merge(dataframe_employees, dataframe_sales, on='employee_id', how='left')

  employee_id        name  total_sales
0           1   Amy Jones          NaN
1           2  Allen Keys          NaN
2           3  Alice Bees      23456.0
3           4  Tim Horton       2512.0

In [111]:
# Выполнить слияние фреймов данных 
pd.merge(dataframe_employees, dataframe_sales, left_on='employee_id', right_on='employee_id')

  employee_id        name  total_sales
0           3  Alice Bees        23456
1           4  Tim Horton         2512

Метод merge поддерживает четыре основных типа соединений:

♦ внутреннее — вернуть только те строки, которые совпадают в обоих фреймах (например, вернуть любую строку, в которой значение employee id появляется одновременно В dataframe_employees И В dataframe_sales);

♦ внешнее— вернуть все строки в обоих фреймах; если строка существует в одном фрейме, но отсутствует в другом, то пропущенные значения заполнить значениями NaN (например, вернуть все строки И В employee_id, И В dataframe_sales);

♦ левое — вернуть все строки из левого фрейма, но только те строки из правого фрейма, которые совпали с левым фреймом; пропущенные значения заполнить значениями NaN (например, вернуть все строки ИЗ dataframe_employees, но только те строки из dataframe saies, которые имеют значение для employee id, появляющееся В dataframe_employees);

♦ правое — вернуть все строки из правого фрейма, но только те строки из левого фрейма, которые совпали с правым фреймом; пропущенные значения заполнить значениями NaN (например, вернуть все строки из dataframe saies, но только те
строки из dataframe_empioyees, которые имеют значение для empioyee_id, появляющееся В dataframe_sales).

In [112]:
df1 = pd.DataFrame({
                     'user_name': ['James Brown', 'Jack White',
                                   'Jane Green'],
                     'country': ['USA', 'USA', 
                                    'France']},
                  index=['ind1', 'ind2', 'ind3'])

df2 = pd.DataFrame({'order_id': [114, 235, 432],
                     'user_id': [2, 4, 3],
                     'order_date': ['2020-02-11', '2020-02-11', 
                                    '2020-02-15'],
                     'OS': ['Android', 'iOS', 'Android']},
                    index=['ind1', 'ind4', 'ind3'])

In [114]:
df1

        user_name country
ind1  James Brown     USA
ind2   Jack White     USA
ind3   Jane Green  France

In [113]:
df1.join(df2)

        user_name country  order_id  user_id  order_date       OS
ind1  James Brown     USA     114.0      2.0  2020-02-11  Android
ind2   Jack White     USA       NaN      NaN         NaN      NaN
ind3   Jane Green  France     432.0      3.0  2020-02-15  Android

In [115]:
df2

      order_id  user_id  order_date       OS
ind1       114        2  2020-02-11  Android
ind4       235        4  2020-02-11      iOS
ind3       432        3  2020-02-15  Android

In [116]:
df2.join(df1)

      order_id  user_id  order_date       OS    user_name country
ind1       114        2  2020-02-11  Android  James Brown     USA
ind4       235        4  2020-02-11      iOS          NaN     NaN
ind3       432        3  2020-02-15  Android   Jane Green  France