1. Import the necessary libraries

In [3]:
import pandas as pd

2. Import the dataset US_Baby_Names_right.csv

3. Assign it to a variable called baby_names

In [7]:
baby_names = pd.read_csv("US_Baby_Names_right.csv")

In [8]:
baby_names.head(5)

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

In [11]:
baby_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 7 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1016395 non-null  int64
 1   Id          1016395 non-null  int64
 2   Name        1016395 non-null  object
 3   Year        1016395 non-null  int64
 4   Gender      1016395 non-null  object
 5   State       1016395 non-null  object
 6   Count       1016395 non-null  int64
dtypes: int64(4), object(3)
memory usage: 54.3+ MB

4. See the first 10 entries

In [13]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

5. Delete the column 'Unnamed: 0' and 'Id'

In [19]:
baby_names.drop(columns=['Unnamed: 0', 'Id'], inplace=True)

In [23]:
baby_names.head(5)

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

      Name  Year Gender State  Count
0     Emma  2004      F    AK     62
1  Madison  2004      F    AK     48
2   Hannah  2004      F    AK     46
3    Grace  2004      F    AK     44
4    Emily  2004      F    AK     41

6. Are there more male or female names in the dataset?

In [25]:
baby_names["Gender"].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

7. Group the dataset by name and assign to names

In [29]:
baby_names[["Name","Count"]].groupby("Name").sum().head(5)

         Count
Name
Aaban       12
Aadan       23
Aadarsh      5
Aaden     3426
Aadhav       6

         Count
Name
Aaban       12
Aadan       23
Aadarsh      5
Aaden     3426
Aadhav       6

In [39]:
baby_names[["Name","Count"]].groupby("Name").sum().shape

(17632, 1)

In [43]:
baby_names[["Name","Count"]].groupby("Name").sum().sort_values("Count",ascending=False).head(5)

           Count
Name
Jacob     242874
Emma      214852
Michael   214405
Ethan     209277
Isabella  204798

8. How many different names exist in the dataset?

In [45]:
len(baby_names[["Name","Count"]].groupby("Name").sum())

17632

9. What is the name with most occurrences?

In [95]:
baby_names[["Name","Count"]].groupby("Name").sum().idxmax()

Count    Jacob
dtype: object

'Jacob'

10. How many different names have the least occurrences?

2578

          Count
Name
Aadarsh       5
Aadin         5
Aaima         5
Aalaya        5
Aaminah       5
...         ...
Zyien         5
Zyire         5
Zykeriah      5
Zykierra      5
Zymari        5

[2578 rows x 1 columns]

11. What is the median name occurrence?

         Count
Name
Aishani     49
Alara       49
Alysse      49
Ameir       49
Anely       49
...        ...
Sriram      49
Trinton     49
Vita        49
Yoni        49
Zuleima     49

[66 rows x 1 columns]

12. Get a summary with the mean, min, max, std and quartiles.

In [53]:
baby_names["Count"].describe()

count    1.016395e+06
mean     3.485012e+01
std      9.739735e+01
min      5.000000e+00
25%      7.000000e+00
50%      1.100000e+01
75%      2.600000e+01
max      4.167000e+03
Name: Count, dtype: float64