## Импорт библиотек

In [1]:
import pandas as pd
import string
import re
import nltk
import pymorphy3

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer

import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
from warnings import filterwarnings
filterwarnings('ignore')

In [3]:
df = pd.read_csv("parse_data.csv").drop('Unnamed: 0', axis=1)

In [4]:
df.head()

,title,description,release_date,tags,rating
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         249 non-null    object
 1   description   249 non-null    object
 2   release_date  249 non-null    object
 3   tags          249 non-null    object
 4   rating        249 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB

## Предварительная обработка данных

In [6]:
def remove_punctuation(text): 
    return "".join([ch if ch not in string.punctuation else ' ' for ch in text])

def remove_numbers(text): 
    return ''.join([i if not i.isdigit() else ' ' for i in text])

def remove_multiple_spaces(text): 
    return re.sub(r'\s+', ' ', text, flags=re.I)

st = '❯ —«»'
def remove_othersymbol(text):
    return ''.join([ch if ch not in st else ' ' for ch in text])

In [7]:
df['prep_text'] = [remove_multiple_spaces(remove_numbers(remove_othersymbol(remove_punctuation(text.lower())))) for text in df['description']]

In [8]:
df.head()

,title,description,release_date,tags,rating,prep_text
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...

In [9]:
russian_stopwords = stopwords.words("russian")

In [10]:
russian_stopwords.extend(['т.д.', 'т', 'д', 'это','который','с','своём','всем','наш', 'свой', 'фильм'])

In [11]:
def tokenize(text):
    t = word_tokenize(text)
    tokens = [token for token in t if token not in russian_stopwords]
    text = " ".join(tokens)
    return text

In [12]:
df['tokenize_text'] = [tokenize(text) for text in df['prep_text']]

In [13]:
df.head()

,title,description,release_date,tags,rating,prep_text,tokenize_text
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...,побег шоушенка считается одним лучших истории ...
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...,ставший классикой своего жанра рассказывающий ...
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...,бэтман вершит правосудие готэме партнерами ста...
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...,продолжение эпохальной саги режиссера френсиса...
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...,присяжных деле убийстве пытается убедить остал...

In [14]:
stemmer = SnowballStemmer("russian")

stem_list = []
for text in (df['tokenize_text']):
    try:
        tokens = word_tokenize(text)
        res = list()
        for word in tokens:
            p = stemmer.stem(word)
            res.append(p)
        text = " ".join(res)
        stem_list.append(text)
    except Exception as e:
        print(e)
        
df['text_stem'] = stem_list

In [15]:
df.head()

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...,побег шоушенка считается одним лучших истории ...,побег шоушенк счита одн лучш истор кин режиссе...
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...,ставший классикой своего жанра рассказывающий ...,ставш классик сво жанр рассказыва истор влияте...
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...,бэтман вершит правосудие готэме партнерами ста...,бэтма верш правосуд готэм партнер станов инспе...
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...,продолжение эпохальной саги режиссера френсиса...,продолжен эпохальн саг режиссер френсис форд к...
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...,присяжных деле убийстве пытается убедить остал...,присяжн дел убийств пыта убед остальн присяжн ...

In [16]:
morph = pymorphy3.MorphAnalyzer(lang='ru')

In [17]:
%%time
lemm_texts_list = []
for text in (df['tokenize_text']):
    try:
        tokens = word_tokenize(text)
        res = list()
        for word in tokens:
            p = morph.parse(word)[0]
            res.append(p.normal_form)
        text = " ".join(res)
        lemm_texts_list.append(text)
    except Exception as e:
        print(e)
    
df['text_lemm'] = lemm_texts_list

CPU times: total: 2.69 s
Wall time: 2.75 s

In [18]:
df.head()

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...,побег шоушенка считается одним лучших истории ...,побег шоушенк счита одн лучш истор кин режиссе...,побег шоушенка считаться один хороший история ...
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...,ставший классикой своего жанра рассказывающий ...,ставш классик сво жанр рассказыва истор влияте...,стать классика свой жанр рассказывать история ...
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...,бэтман вершит правосудие готэме партнерами ста...,бэтма верш правосуд готэм партнер станов инспе...,бэтман вершить правосудие готэма партнёр стано...
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...,продолжение эпохальной саги режиссера френсиса...,продолжен эпохальн саг режиссер френсис форд к...,продолжение эпохальный сага режиссёр френсиса ...
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...,присяжных деле убийстве пытается убедить остал...,присяжн дел убийств пыта убед остальн присяжн ...,присяжный дело убийство пытаться убедить остал...

In [19]:
df['text_lemm'] = [tokenize(text) for text in df['text_lemm']]

In [20]:
df.head()

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...,побег шоушенка считается одним лучших истории ...,побег шоушенк счита одн лучш истор кин режиссе...,побег шоушенка считаться хороший история кино ...
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...,ставший классикой своего жанра рассказывающий ...,ставш классик сво жанр рассказыва истор влияте...,стать классика жанр рассказывать история влият...
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...,бэтман вершит правосудие готэме партнерами ста...,бэтма верш правосуд готэм партнер станов инспе...,бэтман вершить правосудие готэма партнёр стано...
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...,продолжение эпохальной саги режиссера френсиса...,продолжен эпохальн саг режиссер френсис форд к...,продолжение эпохальный сага режиссёр френсиса ...
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...,присяжных деле убийстве пытается убедить остал...,присяжн дел убийств пыта убед остальн присяжн ...,присяжный дело убийство пытаться убедить остал...

## Векторизация текстовых данных

In [21]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=100000990000000000000,
                                 min_df=0.01, stop_words=russian_stopwords,
                                 ngram_range=(1,3))

In [22]:
tfidf_matrix = tfidf_vectorizer.fit_transform(df['text_lemm'])

In [23]:
tfidf_matrix.shape

(249, 659)

## Тематическое моделирование

In [24]:
from sklearn.decomposition import TruncatedSVD

In [25]:
# создание модели LSA
lsa_model = TruncatedSVD(n_components=5, random_state=0)
lsa_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(lsa_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: жизнь, год, история, человек, стать, война, друг, время, город, хороший
Topic 1: война, мировой, мировой война, второй мировой война, второй мировой, второй, рассказывать, американский, история, год
Topic 2: история, год, стать, хороший, реальный, жизнь, рассказывать, реальный история, работать, зритель
Topic 3: дело, убийство, друг, человек, расследование, местный, решать, женщина, полицейский, расследование дело
Topic 4: дело, жизнь, убийство, стать, жена, работа, дочь, решать, полицейский, фрэнк

In [26]:
from sklearn.decomposition import NMF

In [27]:
# создание модели NMF
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(nmf_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: история, год, хороший, реальный, рассказывать, стать, американский, реальный история, время, человек
Topic 1: война, мировой война, мировой, второй, второй мировой, второй мировой война, еврей, время второй мировой, время второй, ужас
Topic 2: друг, город, человек, поиск, новый, жить, отправляться, найти, вместе, день
Topic 3: дело, убийство, полицейский, женщина, расследование, расследование дело, решать, расследовать, убийца, местный
Topic 4: жизнь, работа, стать, ребёнок, депрессия, отношение, деньга, семья, помогать, однако

## Кластеризация

In [28]:
num_clusters = 5

# Метод к-средних - KMeans
from sklearn.cluster import KMeans
km = KMeans(n_clusters=num_clusters, random_state=0)

In [29]:
km.fit(tfidf_matrix)

  File "C:\Users\robhul\anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Users\robhul\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\robhul\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\robhul\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

KMeans(n_clusters=5, random_state=0)

In [30]:
clusterkm = km.labels_.tolist()
df['cluster']= clusterkm

In [31]:
df.head()

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm,cluster
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...,побег шоушенка считается одним лучших истории ...,побег шоушенк счита одн лучш истор кин режиссе...,побег шоушенка считаться хороший история кино ...,2
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...,ставший классикой своего жанра рассказывающий ...,ставш классик сво жанр рассказыва истор влияте...,стать классика жанр рассказывать история влият...,4
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...,бэтман вершит правосудие готэме партнерами ста...,бэтма верш правосуд готэм партнер станов инспе...,бэтман вершить правосудие готэма партнёр стано...,0
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...,продолжение эпохальной саги режиссера френсиса...,продолжен эпохальн саг режиссер френсис форд к...,продолжение эпохальный сага режиссёр френсиса ...,4
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...,присяжных деле убийстве пытается убедить остал...,присяжн дел убийств пыта убед остальн присяжн ...,присяжный дело убийство пытаться убедить остал...,0

In [32]:
df['cluster'].value_counts()

cluster
2    66
3    60
0    43
4    41
1    39
Name: count, dtype: int64

In [33]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [34]:
df[df['cluster']==0]

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm,cluster
2,Темный рыцарь,Бэтман вершит правосудие в Готэме. Его партнер...,12.08.2008,"боевик, драма, кинокомикс, криминал, триллер",9.12/10,бэтман вершит правосудие в готэме его партнера...,бэтман вершит правосудие готэме партнерами ста...,бэтма верш правосуд готэм партнер станов инспе...,бэтман вершить правосудие готэма партнёр стано...,0
4,12 разгневанных мужчин,Один из 12 присяжных в деле об убийстве пытае...,29.07.1957,"детектив, драма",9.15/10,один из присяжных в деле об убийстве пытается ...,присяжных деле убийстве пытается убедить остал...,присяжн дел убийств пыта убед остальн присяжн ...,присяжный дело убийство пытаться убедить остал...,0
9,"Хороший, плохой, злой",Действие происходит в разгар гражданской войны...,23.12.1966,"боевик, вестерн, приключения",8.96/10,действие происходит в разгар гражданской войны...,действие происходит разгар гражданской войны а...,действ происход разгар гражданск войн америк о...,действие происходить разгар гражданский война ...,0
23,Спасти рядового Райана,Вторая Мировая Война. Одна женщина теряет трои...,24.07.1998,"боевик, военный, драма",8.94/10,вторая мировая война одна женщина теряет троих...,вторая мировая война одна женщина теряет троих...,втор миров войн одн женщин теря тро сво сынов ...,второй мировой война женщина терять трое сын ч...,0
25,Жизнь прекрасна,Вторая мировая война. Италия.Фашисты арестовыв...,20.12.1997,"военный, драма, комедия, мелодрама",8.91/10,вторая мировая война италия фашисты арестовыва...,вторая мировая война италия фашисты арестовыва...,втор миров войн итал фашист арестовыва евре от...,второй мировой война италия фашист арестовыват...,0
27,Терминатор 2: Судный день,Первая попытка убить Сару Коннор еще до рожден...,03.07.1991,"боевик, триллер, фантастика",9.41/10,первая попытка убить сару коннор еще до рожден...,первая попытка убить сару коннор рождения сына...,перв попытк уб сар коннор рожден сын провал ск...,первый попытка убить сара коннора рождение сын...,0
34,Гладиатор,Великий генерал Максимус должен был стать насл...,04.05.2000,"боевик, драма, исторический, приключения",9.09/10,великий генерал максимус должен был стать насл...,великий генерал максимус должен стать наследни...,велик генера максимус долж стат наследник кеса...,великий генерал максимус должный стать наследн...,0
35,Король Лев,"На глаза у малыша Симбы погиб его отец, король...",02.07.1994,"детский, драма, комедия, мультфильм, мюзикл, п...",8.95/10,на глаза у малыша симбы погиб его отец король ...,глаза малыша симбы погиб отец король лев муфас...,глаз малыш симб погиб отец корол лев муфас спа...,глаз малыш симб погибнуть отец король лев муфа...,0
49,Новые времена,Легендарный Чарли Чаплин играет роль Маленьког...,11.02.1936,"драма, комедия, мелодрама",9.00/10,легендарный чарли чаплин играет роль маленьког...,легендарный чарли чаплин играет роль маленьког...,легендарн чарл чаплин игра рол маленьк бродяг ...,легендарный чарли чаплин играть роль маленький...,0
58,Индиана Джонс: В поисках утраченного ковчега,Индиана Джонс - известный археолог и специалис...,12.06.1981,"боевик, приключения, триллер",8.83/10,индиана джонс известный археолог и специалист ...,индиана джонс известный археолог специалист ок...,индиа джонс известн археолог специалист оккуль...,индиана джонс известный археолог специалист ок...,0
63,Тропы славы,"1916 год, западный фронт Первой Мировой. Очере...",24.10.1957,"военный, драма",8.17/10,год западный фронт первой мировой очередная с...,год западный фронт первой мировой очередная са...,год западн фронт перв миров очередн самоубийст...,год западный фронт первый мировой очередной са...,0
65,Свидетель обвинения,Рассказ Агаты Кристи о полном сюрпризов суде...,17.12.1957,"детектив, драма, криминал, триллер",8.57/10,рассказ агаты кристи о полном сюрпризов судеб...,рассказ агаты кристи полном сюрпризов судебном...,рассказ агат крист полн сюрприз судебн процесс...,рассказ агат кристи полный сюрприз судебный пр...,0
76,Красота по-американски,Лестер Бернем переживает кризис среднего возра...,18.11.1999,драма,8.47/10,лестер бернем переживает кризис среднего возра...,лестер бернем переживает кризис среднего возра...,лестер берн пережива кризис средн возраст лад ...,лестер бернемой переживать кризис среднее возр...,0
81,Принцесса Мононоке,Отправившийся в путешествие за лекарством от с...,12.07.1997,"аниме, драма, мультфильм, приключения, фэнтези",8.78/10,отправившийся в путешествие за лекарством от с...,отправившийся путешествие лекарством смертельн...,отправ путешеств лекарств смертельн проклят пр...,отправиться путешествие лекарство смертельный ...,0
85,Три идиота,В центре сюжета - три друга. Один из них таинс...,23.12.2009,"драма, комедия",9.07/10,в центре сюжета три друга один из них таинстве...,центре сюжета друга таинственным образом исчез...,центр сюжет друг таинствен образ исчеза дво ос...,центр сюжет друг таинственный образ исчезать д...,0
92,Звездные войны: Эпизод 6 - Возвращение Джедая,"Дарт Вейдер и Император создают новую ""Звезду ...",25.05.1983,"боевик, приключения, фантастика, фэнтези",8.65/10,дарт вейдер и император создают новую звезду с...,дарт вейдер император создают новую звезду сме...,дарт вейдер император созда нов звезд смерт на...,дарт вейдёр император создавать новый звезда с...,0
99,Квартира,Пытающийся поскорее продвинуться по служебно...,16.09.1960,"драма, комедия, мелодрама",8.07/10,пытающийся поскорее продвинуться по служебной...,пытающийся поскорее продвинуться служебной лес...,пыта поскор продвинут служебн лестниц мужчин п...,пытаться скорый продвинуться служебный лестниц...,0
108,Цельнометаллическая оболочка,"Война во Вьетнаме, время морских пехотинцев. Н...",11.09.1987,"боевик, военный, драма",8.61/10,война во вьетнаме время морских пехотинцев нов...,война вьетнаме время морских пехотинцев новобр...,войн вьетнам врем морск пехотинц новобранц жде...,война вьетнам время морской пехотинец новобран...,0
117,Индиана Джонс и последний крестовый поход,В этой части Индиане Джонсу предстоит разыскат...,24.05.1989,"боевик, приключения, триллер",8.85/10,в этой части индиане джонсу предстоит разыскат...,части индиане джонсу предстоит разыскать одну ...,част индиан джонс предсто разыска одн сам таин...,часть индиана джонс предстоять разыскать самый...,0
118,Звездочки на земле,"8-летний Ишан, необычный ребенок, чувствует се...",21.12.2007,"драма, семейный",8.25/10,летний ишан необычный ребенок чувствует себя ...,летний ишан необычный ребенок чувствует одинок...,летн иша необычн ребенок чувств одинок чуж бол...,летний ишан необычный ребёнок чувствовать один...,0
127,Дангал,Национальный чемпион Индии по вольной борьбе С...,22.12.2016,"биографический, драма, спорт",8.60/10,национальный чемпион индии по вольной борьбе с...,национальный чемпион индии вольной борьбе синг...,национальн чемпион инд вольн борьб сингх пхога...,национальный чемпион индия вольный борьба синг...,0
128,Бэтмен: начало,После смерти родителей Брюс Уэйн уезжает из ро...,15.06.2005,"боевик, кинокомикс, криминал, приключения, три...",8.47/10,после смерти родителей брюс уэйн уезжает из ро...,смерти родителей брюс уэйн уезжает родного гор...,смерт родител брюс уэйн уезжа родн город готэм...,смерть родитель брюс уэйн уезжать родный город...,0
136,Отец,Перед тем как отправиться в Париж родная дочь ...,23.12.2020,"драма, комедия",8.18/10,перед тем как отправиться в париж родная дочь ...,отправиться париж родная дочь решает найти сид...,отправ париж родн доч реша найт сиделк единств...,отправиться париж родный дочь решать найти сид...,0
143,Ран,"История жадности, жажды власти и мести.Великий...",01.06.1985,"боевик, военный, драма",7.73/10,история жадности жажды власти и мести великий ...,история жадности жажды власти мести великий ло...,истор жадност жажд власт мест велик лорд реш о...,история жадность жажда власть месть великий ло...,0
152,Телохранитель,"Япония, незадолго до реставрации Мейдзи. Дорог...",25.04.1961,"боевик, приключения",8.50/10,япония незадолго до реставрации мейдзи дорога ...,япония незадолго реставрации мейдзи дорога при...,япон незадолг реставрац мейдз дорог привод оди...,япония незадолго реставрация мейдзь дорога при...,0
155,В поисках Немо,Немо отправился в свой первый учебный день в ш...,30.05.2003,"детский, комедия, мультфильм, приключения, сем...",8.60/10,немо отправился в свой первый учебный день в ш...,немо отправился первый учебный день школе урок...,нем отправ перв учебн ден школ урок друз реш в...,немо отправиться первый учебный день школа уро...,0
156,Пленницы,"Главный герой находит и похищает человека, кот...",04.10.2013,"детектив, драма, криминал, триллер",8.08/10,главный герой находит и похищает человека кото...,главный герой находит похищает человека считае...,главн гер наход похища человек счита как образ...,главный герой находить похищать человек считат...,0
167,"Три билборда на границе Эббинга, Миссури","Отчаявшаяся женщина, после убийства дочери, ре...",01.01.2018,криминал,8.70/10,отчаявшаяся женщина после убийства дочери реша...,отчаявшаяся женщина убийства дочери решает объ...,отчая женщин убийств дочер реша объяв войн мес...,отчаяться женщина убийство дочь решать объявит...,0
174,Воин,Младший сын злоупотребляющего алкоголем бывшег...,09.09.2011,"боевик, драма, спорт",8.35/10,младший сын злоупотребляющего алкоголем бывшег...,младший сын злоупотребляющего алкоголем бывшег...,младш сын злоупотребля алкогол бывш боксер воз...,младший сын злоупотреблять алкоголь бывший бок...,0
177,Гарри Поттер и Дары смерти: Часть 2,Не простое финальное сражение уготовано Гарри ...,14.07.2011,"детектив, драма, приключения, фэнтези",8.58/10,не простое финальное сражение уготовано гарри ...,простое финальное сражение уготовано гарри пот...,прост финальн сражен уготова гарр поттер предс...,простой финальный сражение уготовать гарри пот...,0
180,Безумный Макс 4: Дорога ярости,После апокалипсиса Земля представляет собой бе...,13.05.2015,"боевик, приключения, триллер, фантастика",8.39/10,после апокалипсиса земля представляет собой бе...,апокалипсиса земля представляет собой бескрайн...,апокалипсис земл представля соб бескрайн пусты...,апокалипсис земля представлять бескрайний пуст...,0
184,Перед рассветом,Первый фильм знаменитой трилогии о любви. Моло...,29.03.1995,"драма, мелодрама",8.40/10,первый фильм знаменитой трилогии о любви молод...,первый знаменитой трилогии любви молодой амери...,перв знаменит трилог любв молод американец дже...,первый знаменитый трилогия любовь молодой амер...,0
191,Воспоминания об убийстве,В корейской деревушке происходит убийство двух...,02.05.2003,"боевик, детектив, драма, криминал, триллер",8.53/10,в корейской деревушке происходит убийство двух...,корейской деревушке происходит убийство двух ж...,корейск деревушк происход убийств двух женщин ...,корейский деревушка происходить убийство женщи...,0
193,Золотая лихорадка,Увлекательные приключения Бродяги (Чарли Чапли...,13.07.1925,"вестерн, концерт, мелодрама, приключения, семе...",8.33/10,увлекательные приключения бродяги чарли чаплин...,увлекательные приключения бродяги чарли чаплин...,увлекательн приключен бродяг чарл чаплин отпра...,увлекательный приключение бродяга чарли чаплин...,0
198,Шерлок младший,Киномеханик Китон отчаянно борется за сердце л...,27.10.1924,"комедия, фэнтези",8.50/10,киномеханик китон отчаянно борется за сердце л...,киномеханик китон отчаянно борется сердце люби...,киномеханик китон отчая борет сердц любим одна...,киномеханик китон отчаянно бороться сердце люб...,0
201,Как приручить дракона,"У викинга Хиккупа Хоррендуса Хэддока III, насл...",18.03.2010,"детский, мультфильм, приключения",8.76/10,у викинга хиккупа хоррендуса хэддока iii насле...,викинга хиккупа хоррендуса хэддока iii наследн...,викинг хиккуп хоррендус хэддок iii наследник т...,викинг хиккупа хоррендус хэддок iii наследник ...,0
208,Мистер Смит едет в Вашингтон,Наивный мужчина получает должность в сенате СШ...,25.12.1939,"драма, комедия",8.67/10,наивный мужчина получает должность в сенате сш...,наивный мужчина получает должность сенате сша ...,наивн мужчин получа должност сенат сша план сд...,наивный мужчина получать должность сенат сша п...,0
211,Рокки,Рокки Бальбоа работает на мясном заводе за сме...,01.01.1977,"боевик, спорт",8.73/10,рокки бальбоа работает на мясном заводе за сме...,рокки бальбоа работает мясном заводе смешные д...,рокк бальбо работа мясн завод смешн деньг мечт...,рокк бальбоа работать мясной завод смешной ден...,0
216,Терминатор,"Первая серия знаменитой кинофраншизы ""Терминат...",26.10.1984,"боевик, триллер, фантастика",9.00/10,первая серия знаменитой кинофраншизы терминато...,первая серия знаменитой кинофраншизы терминато...,перв сер знаменит кинофраншиз терминатор компь...,первый серия знаменитый кинофраншиза терминато...,0
220,Пираты Карибского моря: Проклятие Черной жемчу...,"Команда корабля-призрака ""Черная жемчужина"" по...",09.07.2003,"боевик, драма, комедия, мелодрама, приключения...",9.07/10,команда корабля призрака черная жемчужина похи...,команда корабля призрака черная жемчужина похи...,команд корабл призрак черн жемчужин похища доч...,команда корабль призрак чёрный жемчужина похищ...,0
241,Сука любовь,"Три взаимосвязанных истории, герои которых при...",16.04.2000,"драма, триллер",8.10/10,три взаимосвязанных истории герои которых прин...,взаимосвязанных истории герои которых принадле...,взаимосвяза истор геро котор принадлежат разн ...,взаимосвязанный история герой принадлежать раз...,0
242,Ребекка,Семейная пара приезжает в Мэндэрли (поместье Д...,20.06.1940,"детектив, драма, мелодрама, триллер",8.38/10,семейная пара приезжает в мэндэрли поместье де...,семейная пара приезжает мэндэрли поместье де у...,семейн пар приезжа мэндэрл помест де уинтер но...,семейный пара приезжать мэндэрлить поместье де...,0
244,Хладнокровный Люк,Упорный и упрямый мужчина отказывается смирять...,01.12.1967,"драма, криминал",8.00/10,упорный и упрямый мужчина отказывается смирять...,упорный упрямый мужчина отказывается смиряться...,упорн упрям мужчин отказыва смиря тюремн правил,упорный упрямый мужчина отказываться смиряться...,0

In [35]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=100000990000000000000,
                                 min_df=0.01, stop_words=russian_stopwords,
                                 ngram_range=(1,3))
tfidf_matrix = tfidf_vectorizer.fit_transform(df[df['cluster']==0]['text_lemm'])
# создание модели LSA
lsa_model = TruncatedSVD(n_components=5, random_state=0)
lsa_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(lsa_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

# создание модели NMF
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(nmf_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: первый, человек, найти, друг, джонс, убить, коннора, будущее, сын, дело
Topic 1: дело, убийство, конец, решать, война, расследование, дочь, расследование дело, присяжный, присяжный дело
Topic 2: дело, убийство, присяжный дело, присяжный, конец, расследование дело, расследование, ён, остальной, полиция
Topic 3: чарли чаплин, чаплин, бродяга, чарли, золото, отправиться, приключение, чаплин отправиться, отправиться клондайк поиск, отправиться клондайк
Topic 4: джонс, индиана джонс, индиана, реликвия, археолог, опасный, рука, сша, дочь, вернуть
Topic 0: коннора, будущее, убить, человек, первый, сара, машина, убить сара коннора, убить сара, скайнуть
Topic 1: друг, сын, дочь, отправляться, отец, образ, человек, живой, найти, поиск
Topic 2: дело, убийство, конец, решать, расследование дело, война, присяжный дело, присяжный, женщина, расследование
Topic 3: чарли, бродяга, чарли чаплин, чаплин, золото, отправиться клондайк поиск, отправиться клондайк, поиск золото, чаплин отправиться, чарли чаплин отправиться
Topic 4: джонс, индиана джонс, индиана, реликвия, археолог, спилберг, гитлер, адольф, адольф гитлер, хотеть

In [36]:
df[df['cluster']==1]

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm,cluster
7,Криминальное чтиво,Три истории из жизни двух бандитов - Винсента ...,23.09.1994,"драма, криминал",8.94/10,три истории из жизни двух бандитов винсента ве...,истории жизни двух бандитов винсента вега джул...,истор жизн двух бандит винсент вег джулс винфи...,история жизнь бандит винсент вега джулс винфил...,1
10,Форрест Гамп,Форресту Гампу - умственно отсталому человеку ...,23.06.1994,"драма, комедия, мелодрама",9.40/10,форресту гампу умственно отсталому человеку с ...,форресту гампу умственно отсталому человеку до...,форрест гамп умствен отстал человек добр сердц...,форрест гампа умственно отсталый человек добры...,1
12,Бойцовский клуб,"Обычный клерк, угнетенный своей обыденной жизн...",15.10.2009,"драма, криминал, триллер",8.90/10,обычный клерк угнетенный своей обыденной жизнь...,обычный клерк угнетенный своей обыденной жизнь...,обычн клерк угнетен сво обыден жизн торговец с...,обычный клерк угнести обыденный жизнь торговец...,1
15,Матрица,"Он жил своими серыми буднями, он был очень тал...",31.03.1999,"боевик, приключения, триллер, фантастика",9.20/10,он жил своими серыми буднями он был очень тала...,жил своими серыми буднями очень талантливым пр...,жил сво сер будн очен талантлив программист по...,жить серый будни очень талантливый программист...,1
20,Эта замечательная жизнь,Ангел помогает положительному во всех отношени...,07.01.1947,"драма, мелодрама, фэнтези",8.35/10,ангел помогает положительному во всех отношени...,ангел помогает положительному отношениях бизне...,ангел помога положительн отношен бизнесмен око...,ангел помогать положительный отношение бизнесм...,1
29,Назад в будущее,"Марти был обычным выпускником, пока его ""сумас...",15.08.1985,"боевик, комедия, приключения, фантастика",9.15/10,марти был обычным выпускником пока его сумасше...,марти обычным выпускником пока сумасшедший дру...,март обычн выпускник пок сумасшедш друг профес...,марти обычный выпускник пока сумасшедший друг ...,1
33,Психо,"Мэрион Крейн похищает 40 тысяч долларов, сбега...",25.08.1960,"детектив, триллер, ужасы",8.70/10,мэрион крейн похищает тысяч долларов сбегает и...,мэрион крейн похищает тысяч долларов сбегает г...,мэрион крейн похища тысяч доллар сбега город о...,мэрион крейн похищать тысяча доллар сбегать го...,1
36,Человек-паук: Паутина вселенных,Продолжение истории о подростке из Нью-Йорка М...,01.06.2023,"боевик, кинокомикс, мультфильм, приключения, с...",8.60/10,продолжение истории о подростке из нью йорка м...,продолжение истории подростке нью йорка майлзе...,продолжен истор подростк нью йорк майлз морале...,продолжение история подросток нью йорк майлз м...,1
37,Отступники,Полицейские внедряют в окружение мафиози Фрэнк...,26.09.2006,"драма, криминал, триллер",8.80/10,полицейские внедряют в окружение мафиози фрэнк...,полицейские внедряют окружение мафиози фрэнка ...,полицейск внедря окружен мафиоз фрэнк костелл ...,полицейский внедрять окружение мафиози фрэнк к...,1
45,Подозрительные лица,"Полиция, занимаясь расследованием причин взрыв...",19.07.1995,"детектив, криминал, триллер",8.32/10,полиция занимаясь расследованием причин взрыва...,полиция занимаясь расследованием причин взрыва...,полиц заним расследован причин взрыв пирс сан ...,полиция заниматься расследование причина взрыв...,1
48,"Новый кинотеатр ""Парадизо""",Известный кинорежиссер впервые за 30 лет решае...,17.11.1988,"драма, комедия, мелодрама",9.13/10,известный кинорежиссер впервые за лет решается...,известный кинорежиссер впервые лет решается ве...,известн кинорежиссер вперв лет реша вернут род...,известный кинорежиссёр впервые год решаться ве...,1
54,Джанго освобожденный,Противник расизма и рабства доктор Кинг Шульц ...,27.12.2012,"вестерн, драма, кинокомикс",8.54/10,противник расизма и рабства доктор кинг шульц ...,противник расизма рабства доктор кинг шульц ос...,противник расизм рабств доктор кинг шульц осво...,противник расизм рабство доктор кинг шульц осв...,1
56,Помни,Леонард полон решимости отомстить за смерть св...,07.09.2000,"детектив, триллер",8.48/10,леонард полон решимости отомстить за смерть св...,леонард полон решимости отомстить смерть своей...,леонард полон решим отомст смерт сво жен пробл...,леонард полный решимость отомстить смерть жена...,1
73,История игрушек,"Это история о ""секретной жизни"" игрушек, котор...",07.12.1995,"детский, комедия, мультфильм, приключения, сем...",8.54/10,это история о секретной жизни игрушек которую ...,история секретной жизни игрушек которую ведут ...,истор секретн жизн игрушек котор ведут вокруг ...,история секретный жизнь игрушка вести вокруг ч...,1
88,Капернаум,В очень бедной бейрутской семье живет 12-летни...,17.05.2018,драма,8.00/10,в очень бедной бейрутской семье живет летний м...,очень бедной бейрутской семье живет летний мал...,очен бедн бейрутск сем живет летн мальчик зейн...,очень бедный бейрутский семья жить летний маль...,1
101,На север через северо-запад,Невезучий менеджер по работе с клиентами рекла...,17.09.1959,"детектив, мелодрама, приключения, триллер",8.05/10,невезучий менеджер по работе с клиентами рекла...,невезучий менеджер работе клиентами рекламного...,невезуч менеджер работ клиент рекламн агентств...,невезучий менеджер работа клиент рекламный аге...,1
104,Гражданин Кейн,"Жизнеописание Чарльза Фостера Кейна, мультимил...",06.06.1941,"детектив, драма",8.48/10,жизнеописание чарльза фостера кейна мультимилл...,жизнеописание чарльза фостера кейна мультимилл...,жизнеописан чарльз фостер кейн мультимиллионер...,жизнеописание чарльз фостер кейный мультимилли...,1
109,Схватка,Опытный грабитель банков вступает в дуэль с по...,13.01.1996,"боевик, драма, криминал, триллер",8.48/10,опытный грабитель банков вступает в дуэль с по...,опытный грабитель банков вступает дуэль полице...,опытн грабител банк вступа дуэл полицейск очен...,опытный грабитель банк вступать дуэль полицейс...,1
111,Вверх,"Мультфильм о том, как заветная мечта о приключ...",28.05.2009,"детский, комедия, мультфильм, приключения, сем...",8.47/10,мультфильм о том как заветная мечта о приключе...,мультфильм заветная мечта приключениях стать р...,мультфильм заветн мечт приключен стат реальнос...,мультфильм заветный мечта приключение стать ре...,1
114,Развод Надера и Симин,Иранская пара оказывается перед крайне непрост...,16.03.2011,драма,8.80/10,иранская пара оказывается перед крайне непрост...,иранская пара оказывается крайне непростым выб...,иранск пар оказыва крайн непрост выбор уеха ир...,иранский пара оказываться крайне непростой выб...,1
123,Похитители велосипедов,Давно не работавший Антонио Рикки наконец-то н...,24.11.1948,"драма, криминал",8.20/10,давно не работавший антонио рикки наконец то н...,давно работавший антонио рикки находит работу ...,давн работа антон рикк наход работ однак велос...,давно работать антонио рикки находить работа о...,1
134,Шоу Трумана,"В жизни Трумена было все. Все, как у обычных л...",05.06.1998,"драма, фантастика",8.77/10,в жизни трумена было все все как у обычных люд...,жизни трумена обычных людей детство юность раб...,жизн трум обычн люд детств юност работ жен неп...,жизнь трумена обычный человек детство юность р...,1
137,Все о Еве,История упорной и совершенно беспринципной а...,15.01.1951,драма,8.25/10,история упорной и совершенно беспринципной ак...,история упорной совершенно беспринципной актри...,истор упорн совершен беспринципн актрис карьер...,история упорный совершенно беспринципный актри...,1
146,Непрощенный,Бывший преступник и жестокий убийца Уильям Мун...,01.09.1992,"вестерн, драма",8.59/10,бывший преступник и жестокий убийца уильям мун...,бывший преступник жестокий убийца уильям мунни...,бывш преступник жесток убийц уил мун завязыва ...,бывший преступник жестокий убийца уильям мунни...,1
147,Старикам тут не место,В основе фильма лежит роман лауреата Пулитцеро...,21.11.2007,"вестерн, драма, криминал, триллер",8.33/10,в основе фильма лежит роман лауреата пулитцеро...,основе фильма лежит роман лауреата пулитцеровс...,основ фильм леж рома лауреат пулитцеровск прем...,основа лежать роман лауреат пулитцеровский пре...,1
159,Человек-слон,В основе фильма лежит подлинная история Джозеф...,22.12.1980,"биографический, драма, исторический",8.79/10,в основе фильма лежит подлинная история джозеф...,основе фильма лежит подлинная история джозефа ...,основ фильм леж подлин истор джозеф меррик анг...,основа лежать подлинный история джозеф меррик ...,1
160,"В случае убийства набирайте ""М""","Тони Вендис, бывшая звезда большого тенниса, н...",27.10.1954,"криминал, мистика, триллер",8.19/10,тони вендис бывшая звезда большого тенниса нын...,тони вендис бывшая звезда большого тенниса нын...,тон вендис бывш звезд больш теннис нын безрабо...,тони вендис бывший звезда большой теннис ныне ...,1
169,На игле,"Сумасшедший день Марка Рентона, жителя Эдинбур...",23.12.1996,"драма, комедия, криминал",8.34/10,сумасшедший день марка рентона жителя эдинбург...,сумасшедший день марка рентона жителя эдинбург...,сумасшедш ден марк рентон жител эдинбург нача ...,сумасшедший день марк рентон житель эдинбург н...,1
171,Клаус,В небольшую заснеженную и холодную деревушку с...,08.11.2019,"комедия, мультфильм, приключения, семейный",9.18/10,в небольшую заснеженную и холодную деревушку с...,небольшую заснеженную холодную деревушку очень...,небольш заснежен холодн деревушк очен недружел...,небольшой заснеженный холодный деревушка очень...,1
172,"Поймай меня, если сможешь",Фрэнк (ДиКаприо) самый искусный мошенник из вс...,01.01.2003,"биографический, драма, криминал",8.72/10,фрэнк дикаприо самый искусный мошенник из всех...,фрэнк дикаприо самый искусный мошенник мгновен...,фрэнк дикапр сам искусн мошенник мгновен измен...,фрэнк дикаприо самый искусный мошенник мгновен...,1
178,Малышка на миллион,Мэгги Фитцжеральд мечтает стать профессиональн...,14.01.2005,"драма, спорт",8.80/10,мэгги фитцжеральд мечтает стать профессиональн...,мэгги фитцжеральд мечтает стать профессиональн...,мэгг фитцжеральд мечта стат профессиональн бок...,мэгга фитцжеральда мечтать стать профессиональ...,1
183,12 лет рабства,Середина 19-го века. Согласившись на привлекат...,12.12.2013,"биографический, драма, исторический",8.16/10,середина го века согласившись на привлекательн...,середина го века согласившись привлекательное ...,середин го век соглас привлекательн предложен ...,середина го век согласиться привлекательный пр...,1
189,Исчезнувшая,"История о мужчине, который пытается отыскать с...",02.10.2014,"драма, триллер",8.33/10,история о мужчине который пытается отыскать св...,история мужчине пытается отыскать жену таинств...,истор мужчин пыта отыска жен таинствен исчезну...,история мужчина пытаться отыскать жена таинств...,1
190,Общество мертвых поэтов,Тодд Андерсон был крайне застенчивым юношей. Р...,20.07.1989,драма,8.74/10,тодд андерсон был крайне застенчивым юношей ро...,тодд андерсон крайне застенчивым юношей родите...,тодд андерсон крайн застенчив юнош родител отп...,тодда андерсон крайне застенчивый юноша родите...,1
212,Большой Лебовски,"Обычный парень Лебовски по прозвищу «чувак», п...",06.03.1998,"комедия, криминал",8.50/10,обычный парень лебовски по прозвищу чувак по о...,обычный парень лебовски прозвищу чувак ошибке ...,обычн парен лебовск прозвищ чувак ошибк принят...,обычный парень лебовск прозвище чувак ошибка п...,1
217,"Отель ""Руанда""","Десять лет назад, события, которые было страшн...",20.01.2005,"военный, драма, исторический",8.00/10,десять лет назад события которые было страшно ...,десять лет назад события которые страшно вообр...,деся лет назад событ котор страшн вообраз прои...,десять год назад событие страшно вообразить пр...,1
227,Суперсемейка,Глава суперсемейки Боб и его жена Хелен - одни...,05.11.2004,"боевик, детский, комедия, мультфильм, приключе...",8.54/10,глава суперсемейки боб и его жена хелен одни и...,глава суперсемейки боб жена хелен одни самых и...,глав суперсемейк боб жен хел одн сам известн г...,глава суперсемейка боб жена хелен самый извест...,1
228,Телесеть,"Четвертый канал борется за зрителя, теперь даж...",29.01.1977,драма,8.33/10,четвертый канал борется за зрителя теперь даже...,четвертый канал борется зрителя новости станов...,четверт кана борет зрител новост станов скор р...,четвёртый канал бороться зритель новость стано...,1
245,Это случилось однажды ночью,Испорченная богатая наследница убегает из дому...,23.02.1934,"комедия, мелодрама",8.60/10,испорченная богатая наследница убегает из дому...,испорченная богатая наследница убегает дому не...,испорчен богат наследниц убега дом неожида нах...,испортить богатый наследница убегать дом неожи...,1

In [37]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=100000990000000000000,
                                 min_df=0.01, stop_words=russian_stopwords,
                                 ngram_range=(1,3))
tfidf_matrix = tfidf_vectorizer.fit_transform(df[df['cluster']==1]['text_lemm'])
# создание модели LSA
lsa_model = TruncatedSVD(n_components=5, random_state=0)
lsa_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(lsa_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

# создание модели NMF
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(nmf_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: жизнь, человек, жена, история, обычный, работа, миллион, ребёнок, друг, совершенно
Topic 1: работа, го, го век, век, агент, рикки, рабство, меррик, джозеф, принять
Topic 2: жена, рабство, джанго, становиться, зритель, век, го, го век, доктор, находиться
Topic 3: жена, стать, мужчина, лицо, заветный мечта, реальность конец жизнь, мультфильм заветный, мультфильм, мультфильм заветный мечта, заветный мечта приключение
Topic 4: становиться, ночь, мэрион, отец, пока, мир, обычный, тысяча, ребёнок, весь
Topic 0: друг, человек, обычный, жизнь, пока, игрушка, приключение, остаться, марти, отец
Topic 1: полицейский, работа, грабитель, костелло, принять, анджелес, лос анджелес, лос, фрэнк, работать
Topic 2: жена, рабство, джанго, жестокий, становиться, уходить, леонард, предложение, бывший, пытаться
Topic 3: нью йорк, нью, мочь, йорк, взрыв, доллар, история, человек, миллион доллар, год
Topic 4: жизнь, семья, младший, младший брат, брат, мальчик, следить, воспоминание, помогать, однажды

In [38]:
df[df['cluster']==2]

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm,cluster
0,Побег из Шоушенка,"""Побег из Шоушенка"" - фильм, который считается...",06.01.1995,драма,9.44/10,побег из шоушенка фильм который считается одн...,побег шоушенка считается одним лучших истории ...,побег шоушенк счита одн лучш истор кин режиссе...,побег шоушенка считаться хороший история кино ...,2
6,Властелин колец 3: Возвращение Короля,Близится последняя битва за Средиземье. На пут...,17.12.2003,"боевик, приключения, фэнтези",9.48/10,близится последняя битва за средиземье на пути...,близится последняя битва средиземье пути войск...,близ последн битв средизем пут войск саурон ст...,близиться последний битва средиземье путь войс...,2
11,Властелин колец 2: Две крепости,Братство кольца распалось. Фродо и Сэм продолж...,05.12.2002,"боевик, приключения, фэнтези",9.39/10,братство кольца распалось фродо и сэм продолжа...,братство кольца распалось фродо сэм продолжают...,братств кольц распа фрод сэм продолжа пут морд...,братство кольцо распасться фродый сэм продолжа...,2
13,Начало,"В мире будущего, где существуют технологии, по...",14.07.2010,"боевик, триллер, фантастика",9.04/10,в мире будущего где существуют технологии позв...,мире будущего существуют технологии позволяющи...,мир будущ существ технолог позволя проника под...,мир будущее существовать технология позволять ...,2
16,Славные парни,Начинающий молодой гангстер Генри Хилл со свои...,12.09.1990,"биографический, драма, криминал",8.74/10,начинающий молодой гангстер генри хилл со свои...,начинающий молодой гангстер генри хилл своими ...,начина молод гангстер генр хилл сво двум закад...,начинающий молодой гангстер генри хилла закады...,2
17,Пролетая над гнездом кукушки,Один бродяга решил отдохнуть за государственны...,19.11.1975,драма,9.08/10,один бродяга решил отдохнуть за государственны...,бродяга решил отдохнуть государственный счет с...,бродяг реш отдохнут государствен счет симулиру...,бродяга решить отдохнуть государственный счёт ...,2
22,Молчание ягнят,"Клариссе Стерлинг, молодому агенту ФБР, поруче...",14.03.1991,"детектив, драма, криминал, триллер",9.08/10,клариссе стерлинг молодому агенту фбр поручено...,клариссе стерлинг молодому агенту фбр поручено...,кларисс стерлинг молод агент фбр поруч расслед...,кларисса стерлинг молодой агент фбр поручить р...,2
26,Зеленая миля,Чернокожий осужденный Джон Коффи (Майкл Кларк ...,10.12.1999,"драма, криминал, фэнтези",9.18/10,чернокожий осужденный джон коффи майкл кларк д...,чернокожий осужденный джон коффи майкл кларк д...,чернокож осужден джон кофф майкл кларк дунка у...,чернокожий осудить джон коффи майкл кларк дунк...,2
31,Пианист,"Владислав Шпильман - известный музыкант, всеми...",25.09.2002,"биографический, военный, драма, музыка",8.72/10,владислав шпильман известный музыкант всеми си...,владислав шпильман известный музыкант всеми си...,владисла шпильма известн музыкант всем сил пыт...,владислав шпильман известный музыкант весь сил...,2
38,Одержимость,"История о молодом музыканте, преодолевающем ра...",13.11.2014,"драма, музыка",8.78/10,история о молодом музыканте преодолевающем раз...,история молодом музыканте преодолевающем разли...,истор молод музыкант преодолева различн препят...,история молодой музыкант преодолевать различны...,2
44,Дюна: Часть вторая,"Герцог Пол Атрейдес присоединяется к фрименам,...",28.02.2024,"боевик, драма, приключения, фантастика",7.98/10,герцог пол атрейдес присоединяется к фрименам ...,герцог пол атрейдес присоединяется фрименам ст...,герцог пол атрейдес присоединя фримен стат муа...,герцог пол атрейдес присоединяться фримя стать...,2
46,Касабланка,Действие происходит во время второй мировой во...,09.12.1942,"драма, мелодрама",8.82/10,действие происходит во время второй мировой во...,действие происходит время второй мировой войны...,действ происход врем втор миров войн владелец ...,действие происходить время второй мировой войн...,2
50,Чужой,"Команда космического грузовика ""Ностромо"" выхо...",21.07.1979,"триллер, ужасы, фантастика",8.87/10,команда космического грузовика ностромо выходи...,команда космического грузовика ностромо выходи...,команд космическ грузовик ностром выход гиперс...,команда космический грузовик ностромый выходит...,2
51,Окно во двор,"Прикованный к инвалидному креслу фотограф, шп...",14.01.1955,"детектив, криминал, триллер",8.57/10,прикованный к инвалидному креслу фотограф шпио...,прикованный инвалидному креслу фотограф шпионя...,прикова инвалидн кресл фотограф шпионя сво сос...,приковать инвалидный кресло фотограф шпионить ...,2
62,Мстители 3: Война бесконечности,"Мстители и Стражи Галактики объединяются, чтоб...",27.04.2018,"боевик, кинокомикс, приключения, фантастика",9.04/10,мстители и стражи галактики объединяются чтобы...,мстители стражи галактики объединяются противо...,мстител страж галактик объединя противостоя та...,мститель стража галактика объединяться противо...,2
66,Сияние,"Джек Торранс, его жена и сын жили в изолирован...",26.09.1980,"мистика, триллер, ужасы",8.57/10,джек торранс его жена и сын жили в изолированн...,джек торранс жена сын жили изолированном отеле...,джек торранс жен сын жил изолирова отел однажд...,джек торранс жена сын жить изолировать отель о...,2
67,Великий диктатор,"История про простого еврейского цирюльника, пр...",16.12.1940,"военный, драма, комедия",8.90/10,история про простого еврейского цирюльника про...,история простого еврейского цирюльника прошедш...,истор прост еврейск цирюльник прошедш окоп вел...,история простой еврейский цирюльник прошедшее ...,2
72,Амадей,Антонио Сальери считал музыку Моцарта божестве...,08.10.1984,"биографический, драма, музыка",8.50/10,антонио сальери считал музыку моцарта божестве...,антонио сальери считал музыку моцарта божестве...,антон сальер счита музык моцарт божествен мечт...,антонио сальери считать музыка моцарт божестве...,2
78,Подводная лодка,"1942 год, немецкий подводный флот. Идет битва ...",17.09.1981,"боевик, военный, драма, исторический",8.88/10,год немецкий подводный флот идет битва за атл...,год немецкий подводный флот идет битва атланти...,год немецк подводн флот идет битв атлантик ист...,год немецкий подводный флот идти битва атланти...,2
79,Храброе сердце,"Шотландия, XIII век. Легендарный национальный ...",24.05.1995,"биографический, боевик, военный, драма, истори...",9.07/10,шотландия xiii век легендарный национальный ге...,шотландия xiii век легендарный национальный ге...,шотланд xiii век легендарн национальн гер уил ...,шотландия xiii век легендарный национальный ге...,2
80,Умница Уилл Хантинг,Уилл Хантинг вырос в пригороде Бостона. Он поч...,09.01.1998,драма,8.53/10,уилл хантинг вырос в пригороде бостона он почт...,уилл хантинг вырос пригороде бостона учился ле...,уилл хантинг вырос пригород бостон уч лет пост...,уилла хантинг вырасти пригород бостон учиться ...,2
83,Твое имя,"Мицуха - скромная девушка, живущая в маленьком...",26.08.2016,"аниме, драма, мелодрама, мультфильм, фэнтези",8.39/10,мицуха скромная девушка живущая в маленьком пр...,мицуха скромная девушка живущая маленьком пров...,мицух скромн девушк живущ маленьк провинциальн...,мицуха скромный девушка жить маленький провинц...,2
84,Рай и ад,"Как близко иной раз беда проходит мимо нас, но...",01.03.1963,"драма, криминал, мистика, триллер",8.33/10,как близко иной раз беда проходит мимо нас но ...,близко иной беда проходит мимо многи способны ...,близк ин бед проход мим мног способн оцен дар ...,близко иной беда проходить мимо многа способны...,2
87,Поющие под дождем,"Фильм ""Поющие под дождем"" - культовый музыкаль...",11.04.1952,"комедия, мелодрама, мюзикл",8.86/10,фильм поющие под дождем культовый музыкальный ...,поющие дождем культовый музыкальный снятый год...,поющ дожд культов музыкальн снят год режиссер ...,петь дождь культовый музыкальный снять год реж...,2
89,Иди и смотри,"Во время Великой Отечественной войны, на оккуп...",10.07.1985,"военный, драма",8.67/10,во время великой отечественной войны на оккупи...,время великой отечественной войны оккупированн...,врем велик отечествен войн оккупирова фашист т...,время великий отечественный война оккупировать...,2
91,История Игрушек 3: Большой Побег,"После того, как повзрослевший малыш Энди уезжа...",16.06.2010,"детский, комедия, мультфильм, приключения, сем...",8.57/10,после того как повзрослевший малыш энди уезжае...,повзрослевший малыш энди уезжает учиться колле...,повзрослевш малыш энд уезжа уч колледж стар др...,повзрослеть малыш энди уезжать учиться колледж...,2
93,Вечное сияние чистого разума,"Однажды Джоэл узнает, что его подружка Клемент...",19.03.2004,"драма, мелодрама",8.81/10,однажды джоэл узнает что его подружка клементи...,однажды джоэл узнает подружка клементина решил...,однажд джоэл узна подружк клементин реш стерет...,однажды джоэл узнать подружка клементина решит...,2
94,Охота,"Жизнь 40-летнего учителя, недавно пережившего ...",25.10.2012,драма,8.57/10,жизнь летнего учителя недавно пережившего неве...,жизнь летнего учителя недавно пережившего неве...,жизн летн учител недавн переж невероятн тяжел ...,жизнь летний учитель недавно пережить невероят...,2
95,2001 год: Космическая одиссея,Американцы обнаруживают погребенный на луне ар...,02.04.1968,"детектив, приключения, фантастика",8.45/10,американцы обнаруживают погребенный на луне ар...,американцы обнаруживают погребенный луне артеф...,американц обнаружива погребен лун артефакт вне...,американец обнаруживать погрести луна артефакт...,2
96,Жить,Кандзи Ватанабэ жить осталось недолго - у него...,09.10.1952,драма,9.00/10,кандзи ватанабэ жить осталось недолго у него о...,кандзи ватанабэ жить осталось недолго обнаружи...,кандз ватанабэ жит оста недолг обнаруж рак жел...,кандзь ватанабэ жить остаться недолго обнаружи...,2
100,Пожары,Желая исполнить последнее желание своей матер...,12.01.2011,"военный, детектив, драма",7.38/10,желая исполнить последнее желание своей матер...,желая исполнить последнее желание своей матери...,жел исполн последн желан сво матер брат сестр ...,желать исполнить последний желание мать брат с...,2
107,Головокружение,"Джон ""Скотти"" Фергюсон - детектив в отставке. ...",22.07.1958,"мелодрама, мистика, триллер",8.18/10,джон скотти фергюсон детектив в отставке когда...,джон скотти фергюсон детектив отставке подавал...,джон скотт фергюсон детект отставк подава боль...,джон скотти фергюсон детектив отставка подават...,2
113,Убить пересмешника,Америка времен Великой Депрессии. Адвокат из ...,25.12.1962,"детектив, драма, криминал",8.75/10,америка времен великой депрессии адвокат из ал...,америка времен великой депрессии адвокат алаба...,америк врем велик депресс адвокат алабам аттик...,америка время великий депрессия адвокат алабам...,2
116,Крепкий орешек,Полицейский Джон Макклэйн в одиночку сражается...,15.07.1988,"боевик, криминал, триллер",8.82/10,полицейский джон макклэйн в одиночку сражается...,полицейский джон макклэйн одиночку сражается б...,полицейск джон макклэйн одиночк сража банд тер...,полицейский джон макклэйн одиночка сражаться б...,2
126,Бункер,Апрель 1945-го. С Востока на Германию идут рус...,08.09.2004,"биографический, военный, драма, исторический",8.16/10,апрель го с востока на германию идут русские в...,апрель го востока германию идут русские войска...,апрел го восток герман идут русск войск запад ...,апрель го восток германия идти русский войско ...,2
133,Малыш,Бродяга берет на себя заботу о брошенном матер...,06.02.1921,"драма, комедия, семейный",8.67/10,бродяга берет на себя заботу о брошенном матер...,бродяга берет заботу брошенном матерью ребенке...,бродяг берет забот брошен матер ребенк однак в...,бродяга брать забота бросить мать ребёнок одна...,2
138,Остров проклятых,Действие фильма происходит в 1954 году. Леонар...,18.02.2010,"детектив, драма, триллер",8.75/10,действие фильма происходит в году леонардо дик...,действие фильма происходит году леонардо дикап...,действ фильм происход год леонард дикапр игра ...,действие происходить год леонардо дикаприо игр...,2
141,Топ Ган: Мэверик,После более чем тридцатилетней службы в качест...,25.05.2022,"боевик, драма",8.53/10,после более чем тридцатилетней службы в качест...,тридцатилетней службы качестве одного лучших а...,тридцатилетн служб качеств одн лучш авиатор во...,тридцатилетний служба качество хороший авиатор...,2
149,Игры разума,Фильм основан на реальных событиях. Талантливы...,04.01.2002,"биографический, драма",8.85/10,фильм основан на реальных событиях талантливый...,основан реальных событиях талантливый ученый м...,основа реальн событ талантлив учен математик д...,основать реальный событие талантливый учёный м...,2
150,Убить Билла,"Черная Мамба была лучшей в банде убийц ""Смерто...",10.10.2003,"боевик, драма, криминал, триллер",8.22/10,черная мамба была лучшей в банде убийц смертон...,черная мамба лучшей банде убийц смертоносные г...,черн мамб лучш банд убийц смертоносн гадюк пре...,чёрный мамба хороший банда убийца смертоносный...,2
154,Монти Пайтон и священный Грааль,Король Артур и его рыцари пускаются на малобю...,10.05.1975,"комедия, приключения",7.75/10,король артур и его рыцари пускаются на малобю...,король артур рыцари пускаются малобюджетные по...,корол артур рыцар пуска малобюджетн поиск свящ...,король артур рыцарь пускаться малобюджетный по...,2
157,Ходячий замок,Юная София проклята ведьмой и вынуждена жить в...,05.09.2005,"аниме, мелодрама, мультфильм, приключения, фан...",8.48/10,юная софия проклята ведьмой и вынуждена жить в...,юная софия проклята ведьмой вынуждена жить тел...,юн соф проклят ведьм вынужд жит тел старух гор...,юный софия проклятый ведьма вынудить жить тело...,2
162,Унесенные ветром,"""Унесенные ветром"" - это культовый фильм-эпопе...",01.05.1940,"военный, драма, мелодрама",8.80/10,унесенные ветром это культовый фильм эпопея в...,унесенные ветром культовый эпопея выпущенный г...,унесен ветр культов эпопе выпущен год режиссер...,унести ветер культовый эпопея выпустить год ре...,2
164,Тайна в его глазах,"Бенджамин Эспозито 30 лет назад дал слово, что...",13.08.2009,"детектив, драма, криминал, мелодрама, триллер",7.73/10,бенджамин эспозито лет назад дал слово что най...,бенджамин эспозито лет назад дал слово найдет ...,бенджамин эспозит лет назад дал слов найдет уб...,бенджамин эспозитый год назад дать слово найти...,2
166,"""V"" значит Вендетта",Фильм рассказывает о Мстителе в маске Гая Фокс...,15.03.2006,"боевик, кинокомикс, триллер, фантастика",8.46/10,фильм рассказывает о мстителе в маске гая фокс...,рассказывает мстителе маске гая фокса уивинг о...,рассказыва мстител маск га фокс уивинг одинок ...,рассказывать мститель маска гай фокса уивинга ...,2
168,Бешеный бык,Когда Джейк ЛаМотт вступил на ринг и победил с...,05.02.1981,"биографический, драма, спорт",8.70/10,когда джейк ламотт вступил на ринг и победил с...,джейк ламотт вступил ринг победил своего оппон...,джейк ламотт вступ ринг побед сво оппонент ста...,джейк ламотт вступить ринг победить оппонент с...,2
173,Фарго,Джерри работал в небольшом дилерском магазине ...,05.04.1996,"драма, криминал, триллер",8.38/10,джерри работал в небольшом дилерском магазине ...,джерри работал небольшом дилерском магазине св...,джерр работа небольш дилерск магазин сво свекр...,джерри работать небольшой дилерский магазин св...,2
182,Бен-Гур,"Фильм ""Бен-Гур - это шедевр кинематографа, кот...",10.12.1959,"боевик, драма, исторический, мелодрама, приклю...",8.87/10,фильм бен гур это шедевр кинематографа который...,бен гур шедевр кинематографа стал классикой ми...,бен гур шедевр кинематограф стал классик миров...,бен гур шедевр кинематограф стать классика мир...,2
185,Барри Линдон,"18 век, небольшая деревня в Ирландии.Редмонд Б...",18.12.1975,"военный, драма, мелодрама",8.46/10,век небольшая деревня в ирландии редмонд барр...,век небольшая деревня ирландии редмонд барри м...,век небольш деревн ирланд редмонд барр мальчиш...,век небольшой деревня ирландия редмонд барри м...,2
186,Бегущий по лезвию,"Лос-Анджелес, 2019 год. Бывшего детектива внов...",25.06.1982,"боевик, драма, нуар, триллер, фантастика",8.40/10,лос анджелес год бывшего детектива вновь вызыв...,лос анджелес год бывшего детектива вновь вызыв...,лос анджелес год бывш детектив внов вызыва раб...,лос анджелес год бывший детектив вновь вызыват...,2
192,Во имя отца,"Это история Джерри Конлона, мелкого грабителя ...",12.12.1993,"биографический, драма",7.50/10,это история джерри конлона мелкого грабителя и...,история джерри конлона мелкого грабителя белфа...,истор джерр конлон мелк грабител белфаст однаж...,история джерри конлоно мелкий грабитель белфас...,2
194,Корпорация монстров,Они монстры. Их работа - по ночам выпрыгивать ...,14.11.2001,"комедия, мультфильм, семейный, фэнтези",8.80/10,они монстры их работа по ночам выпрыгивать из ...,монстры работа ночам выпрыгивать дверей шкафа ...,монстр работ ноч выпрыгива двер шкаф детск ком...,монстр работа ночь выпрыгивать дверь шкаф детс...,2
196,Охотник на оленей,"Майкл, Стивен и Ник молодые работники завода и...",22.09.1979,"военный, драма, триллер",8.55/10,майкл стивен и ник молодые работники завода из...,майкл стивен ник молодые работники завода пенс...,майкл стив ник молод работник завод пенсильван...,майкл стивен ник молодой работник завод пенсил...,2
202,В порту,"Бывший боец, а ныне простой портовый грузчик ...",24.06.1954,"драма, криминал, мелодрама",7.78/10,бывший боец а ныне простой портовый грузчик те...,бывший боец ныне простой портовый грузчик терр...,бывш боец нын прост портов грузчик терр мэлло ...,бывший боец ныне простой портовый грузчик терр...,2
210,Логан,2029 год. Вот уже больше двадцати лет на Земле...,02.03.2017,"боевик, драма, кинокомикс, триллер, фантастика",8.51/10,год вот уже больше двадцати лет на земле не р...,год двадцати лет земле рождается мутант постар...,год двадцат лет земл рожда мутант постаревш ра...,год двадцать год земля рождаться мутант постар...,2
213,Седьмая печать,"Середина XIV века. Рыцарь Антониус Блок, в соп...",16.02.1957,"драма, фэнтези",8.52/10,середина xiv века рыцарь антониус блок в сопро...,середина xiv века рыцарь антониус блок сопрово...,середин xiv век рыцар антониус блок сопровожде...,середина xiv век рыцарь антониус блок сопровож...,2
214,Комната,Современный рассказ о безграничной любви между...,04.09.2015,"драма, триллер",8.20/10,современный рассказ о безграничной любви между...,современный рассказ безграничной любви матерью...,современ рассказ безграничн любв матер ребенк ...,современный рассказ безграничный любовь мать р...,2
219,Ненависть,Молодой хулиган Абдель попадает в больницу пос...,31.05.1995,"драма, криминал",7.57/10,молодой хулиган абдель попадает в больницу пос...,молодой хулиган абдель попадает больницу участ...,молод хулига абдел попада больниц участ погром...,молодой хулиган абдель попадать больница участ...,2
222,Страсти Жанны д`Арк,Хроника суда над Жаной д`Арк по обвинению в ер...,21.04.1928,"биографический, драма, исторический",8.50/10,хроника суда над жаной д арк по обвинению в ер...,хроника суда жаной арк обвинению ереси церковн...,хроник суд жан арк обвинен ерес церковн суд пы...,хроника суд жана арк обвинение ересь церковный...,2
229,Волшебник страны Оз,Фильм снят по мотивам знаменитого произведения...,25.08.1939,"приключения, фэнтези",7.38/10,фильм снят по мотивам знаменитого произведения...,снят мотивам знаменитого произведения фрэнка б...,снят мотив знаменит произведен фрэнк баум,снятой мотив знаменитый произведение фрэнк баум,2
230,Останься со мной,Четверо друзей отправились на поиски убитого т...,04.11.1986,"драма, приключения",7.69/10,четверо друзей отправились на поиски убитого т...,четверо друзей отправились поиски убитого тинэ...,четвер друз отправ поиск убит тинэйджер ровесн...,четверо друг отправиться поиск убитый тинэйдже...,2
232,Звуки музыки,Живущая в Австрии девушка-сирота соглашается с...,29.03.1965,"биографический, драма, мюзикл, семейный",9.06/10,живущая в австрии девушка сирота соглашается с...,живущая австрии девушка сирота соглашается ста...,живущ австр девушк сирот соглаша стат гувернан...,жить австрия девушка сирота соглашаться стать ...,2

In [39]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=100000990000000000000,
                                 min_df=0.01, stop_words=russian_stopwords,
                                 ngram_range=(1,3))
tfidf_matrix = tfidf_vectorizer.fit_transform(df[df['cluster']==2]['text_lemm'])
# создание модели LSA
lsa_model = TruncatedSVD(n_components=5, random_state=0)
lsa_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(lsa_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

# создание модели NMF
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(nmf_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: стать, год, хороший, жизнь, история, время, война, мировой, сын, зритель
Topic 1: последний, мать, вскоре, поиск, странный, деньга, барри, друг, великий, джерри
Topic 2: время великий депрессия, великий депрессия, время великий, великий, депрессия, чернокожий, защищать ложный обвинить, депрессия адвокат алабама, алабама аттикус, алабама аттикус финч
Topic 3: снятой мотив, мотив, снятой, баум, знаменитый произведение, мотив знаменитый произведение, снятой мотив знаменитый, мотив знаменитый, произведение фрэнк баум, произведение фрэнк
Topic 4: стать, ребёнок, великий депрессия, время великий депрессия, депрессия, время великий, великий, подобный, сальери, моцарт
Topic 0: хороший, кинематограф, история, стать, зритель, музыкальный, также, шоушенка, побег, побег шоушенка
Topic 1: ребёнок, мать, сын, девушка, комната, год, детский, джек, жить, вскоре
Topic 2: время великий, великий депрессия, время великий депрессия, великий, депрессия, время, защищать, америка время, защищать ложный обвинить, защищать ложный
Topic 3: немец, война, музыкант, пытаться, время второй мировой, время второй, касабланка, муж, рик, год
Topic 4: поиск, джерри, последний, деньга, рыцарь, битва, отправляться, путь, игра, человек

In [40]:
df[df['cluster']==3]

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm,cluster
5,Список Шиндлера,Немецкий фабрикант и член нацистской партии Ос...,30.11.1993,"биографический, военный, драма, исторический",9.19/10,немецкий фабрикант и член нацистской партии ос...,немецкий фабрикант член нацистской партии оска...,немецк фабрикант член нацистск парт оскар шинд...,немецкий фабрикант член нацистский партия оска...,3
8,Властелин колец: Братство кольца,Поиски великого кольца Саурона завершены. Оно ...,19.12.2001,"боевик, приключения, фэнтези",9.33/10,поиски великого кольца саурона завершены оно п...,поиски великого кольца саурона завершены оно п...,поиск велик кольц саурон заверш он попа рук хо...,поиск великий кольцо саурон завершить оно попа...,3
14,Звездные войны: Эпизод 5 - Империя наносит отв...,В Галактике идет война. Имперские войска наход...,21.05.1980,"боевик, приключения, фантастика, фэнтези",8.98/10,в галактике идет война имперские войска находя...,галактике идет война имперские войска находят ...,галактик идет войн имперск войск наход баз пов...,галактика идти война имперский войско находить...,3
19,Семь,Двое полицейских расследуют дело серийного уби...,22.09.1995,"детектив, драма, криминал, триллер",8.88/10,двое полицейских расследуют дело серийного уби...,двое полицейских расследуют дело серийного уби...,дво полицейск расслед дел серийн убийц действ ...,двое полицейский расследовать дело серийный уб...,3
21,Семь самураев,"Исторический фильм, действие которого происход...",26.04.1954,"боевик, драма, приключения",8.97/10,исторический фильм действие которого происходи...,исторический действие которого происходит сред...,историческ действ котор происход средневеков я...,исторический действие происходить средневековы...,3
24,Город Бога,Город Бога - нищий квартал Рио-де-Жанейро. Луч...,30.08.2002,"драма, криминал, триллер",8.41/10,город бога нищий квартал рио де жанейро лучше ...,город бога нищий квартал рио де жанейро появля...,город бог нищ кварта ри де жанейр появля взрос...,город бог нищий квартал рио де жанейро появлят...,3
30,Унесенные призраками,Маленькая Тихиро вместе с мамой и папой переез...,20.07.2001,"аниме, детектив, мультфильм, приключения, семе...",8.77/10,маленькая тихиро вместе с мамой и папой переез...,маленькая тихиро вместе мамой папой переезжают...,маленьк тихир вмест мам пап переезжа нов дом з...,маленький тихиро вместе мама папа переезжать н...,3
41,Могила светлячков,Трагическая история о маленьком мальчике и его...,16.04.1988,"аниме, военный, драма, мультфильм",8.61/10,трагическая история о маленьком мальчике и его...,трагическая история маленьком мальчике младшей...,трагическ истор маленьк мальчик младш сестренк...,трагический история маленький мальчик младший ...,3
42,Престиж,В этой вольной экранизации романа Кристофера П...,17.10.2006,"детектив, драма, триллер, фантастика, фэнтези",8.79/10,в этой вольной экранизации романа кристофера п...,вольной экранизации романа кристофера приста р...,вольн экранизац рома кристофер прист реч идет ...,вольный экранизация роман кристофер пристый ре...,3
43,Харакири,Хансиро Цугумо когда-то был самураем в клане Ф...,16.09.1962,"боевик, драма, исторический",9.67/10,хансиро цугумо когда то был самураем в клане ф...,хансиро цугумо самураем клане фокушима дом пот...,хансир цугум самура клан фокушим дом потерпел ...,хансиро цугумо самурай клан фокушить дом потер...,3
57,ВАЛЛ-И,Далекое будущее. Земля напоминает большую мус...,27.06.2008,"детский, комедия, мелодрама, мультфильм, семей...",8.87/10,далекое будущее земля напоминает большую мусор...,далекое будущее земля напоминает большую мусор...,далек будущ земл напомина больш мусорн корзин ...,далёкий будущее земля напоминать больший мусор...,3
61,Сансет бульвар,Сценарист по найму пишет сценарий для некогда ...,25.08.1950,"драма, нуар",8.89/10,сценарист по найму пишет сценарий для некогда ...,сценарист найму пишет сценарий некогда очень п...,сценарист найм пишет сценар некогд очен популя...,сценарист нанять писать сценарий некогда очень...,3
68,Чужие,"Спасательную капсулу, с выжившей после схватки...",18.07.1986,"боевик, триллер, ужасы, фантастика",9.06/10,спасательную капсулу с выжившей после схватки ...,спасательную капсулу выжившей схватки чужим эл...,спасательн капсул выж схватк чуж элл рипл обна...,спасательный капсула выжить схватка чужой элле...,3
69,Бесславные ублюдки,Группа евреев американского происхождения веде...,19.08.2009,"боевик, военный, драма, приключения",8.24/10,группа евреев американского происхождения веде...,группа евреев американского происхождения веде...,групп евре американск происхожден ведет беспощ...,группа еврей американский происхождение вести ...,3
70,Темный рыцарь 2: Возрождение легенды,"Бэтмен, восемь лет назад взявший на себе ответ...",19.07.2012,"боевик, драма, кинокомикс, криминал, триллер, ...",8.26/10,бэтмен восемь лет назад взявший на себе ответс...,бэтмен восемь лет назад взявший ответственност...,бэтм восем лет назад взявш ответствен преступл...,бэтмена восемь год назад взять ответственность...,3
71,Тайна Коко,"Раскрытие секрета, не дававшего покоя целым по...",22.11.2017,"детектив, комедия, мультфильм, мюзикл, приключ...",8.76/10,раскрытие секрета не дававшего покоя целым пок...,раскрытие секрета дававшего покоя целым поколе...,раскрыт секрет дава поко цел поколен привод не...,раскрытие секрет давать покой целый поколение ...,3
74,"Доктор Стрейнджлав, или Как я научился не волн...",Сумасшедший генерал запускает процесс «ядерног...,29.01.1964,"комедия, триллер",7.90/10,сумасшедший генерал запускает процесс ядерного...,сумасшедший генерал запускает процесс ядерного...,сумасшедш генера запуска процесс ядерн холок г...,сумасшедший генерал запускать процесс ядерный ...,3
75,Олдбой,Похищенный и заключенный в неволю на 15 лет О ...,21.11.2003,"боевик, детектив, драма, кинокомикс, триллер",8.49/10,похищенный и заключенный в неволю на лет о дэ ...,похищенный заключенный неволю лет дэ су освобо...,похищен заключен невол лет дэ су освобожд осво...,похитить заключить неволить год дэ су освободи...,3
77,Мстители 4: Финал,Танос завладел всеми Камнями бесконечности. По...,24.04.2019,"боевик, кинокомикс, приключения, фантастика, ф...",8.18/10,танос завладел всеми камнями бесконечности пол...,танос завладел всеми камнями бесконечности пол...,танос завладел всем камн бесконечн половин раз...,танос завладеть весь камень бесконечность поло...,3
86,Однажды в Америке,Это случилось однажды в Америке...Безумные 20-...,23.05.1984,"драма, криминал",8.92/10,это случилось однажды в америке безумные е год...,случилось однажды америке безумные е годы прош...,случ однажд америк безумн е год прошл век сам ...,случиться однажды америка безумный год прошлое...,3
103,Лицо со шрамом,На поиски Великой Американской Мечты ринулись ...,09.02.1984,"боевик, драма, криминал",8.61/10,на поиски великой американской мечты ринулись ...,поиски великой американской мечты ринулись куб...,поиск велик американск мечт ринул кубинск беже...,поиск великий американский мечта ринуться куби...,3
105,Двойная страховка,Уолтер Нефф - страховой агент. В один из дней ...,27.11.1944,"драма, криминал, триллер",8.25/10,уолтер нефф страховой агент в один из дней он ...,уолтер нефф страховой агент дней отправляется ...,уолтер нефф страхов агент дне отправля дом кли...,уолтер нефф страховой агент день отправляться ...,3
106,М убийца,Страшный маньяк появился в городе. Его жертвам...,11.05.1931,"драма, криминал, нуар, триллер",8.09/10,страшный маньяк появился в городе его жертвами...,страшный маньяк появился городе жертвами стано...,страшн маньяк появ город жертв станов маленьк ...,страшный маньяк появиться город жертва станови...,3
112,Заводной апельсин,Помещенного в тюрьму харизматичного и безжалос...,13.01.1972,"драма, криминал, триллер, фантастика",8.43/10,помещенного в тюрьму харизматичного и безжалос...,помещенного тюрьму харизматичного безжалостног...,помещен тюрьм харизматичн безжалостн лидер под...,поместить тюрьма харизматичный безжалостный ли...,3
119,Метрополис,"В городе будущего, жители которого четко разде...",21.03.1927,"драма, триллер, фантастика",8.56/10,в городе будущего жители которого четко раздел...,городе будущего жители которого четко разделен...,город будущ жител котор четк раздел класс клас...,город будущее житель чётко разделить класс кла...,3
120,Большой куш,"Беспринципный боксерский промоутер, жестокий б...",01.09.2000,"криминал, триллер",8.63/10,беспринципный боксерский промоутер жестокий бу...,беспринципный боксерский промоутер жестокий бу...,беспринципн боксерск промоутер жесток букмекер...,беспринципный боксёрский промоутер жестокий бу...,3
122,Секреты Лос-Анджелеса,"Лос-Анджелес 50х, город в стиле нуар. Полиция ...",16.10.1997,"детектив, драма, криминал, нуар, триллер",8.55/10,лос анджелес х город в стиле нуар полиция корр...,лос анджелес х город стиле нуар полиция коррум...,лос анджелес х город стил нуар полиц коррумпир...,лос анджелес х город стиль нуар полиция коррум...,3
125,Таксист,Он прошел всю войну во Вьетнаме. Он видел ВСЕ....,22.03.1976,"драма, криминал, нуар, триллер",8.51/10,он прошел всю войну во вьетнаме он видел все н...,прошел войну вьетнаме видел простой таксист ра...,прошел войн вьетнам видел прост таксист работа...,пройти война вьетнам видеть простой таксист ра...,3
129,На несколько долларов больше,Два охотника за головами из совершенно разных ...,18.12.1965,"боевик, вестерн, криминал, приключения",8.84/10,два охотника за головами из совершенно разных ...,охотника головами совершенно разных соображени...,охотник голов совершен разн соображен объединя...,охотник голова совершенно разный соображение о...,3
131,Зеленая книга,Фильм рассказывает реальную историю простого и...,11.09.2018,"биографический, драма, комедия, музыка",8.39/10,фильм рассказывает реальную историю простого и...,рассказывает реальную историю простого итало а...,рассказыва реальн истор прост ита американск в...,рассказывать реальный история простой италый а...,3
135,Нюрнбергский процесс,1948 год. Американский суд в оккупированной Ге...,18.12.1961,"биографический, драма, исторический",8.00/10,год американский суд в оккупированной германи...,год американский суд оккупированной германии с...,год американск суд оккупирова герман суд четыр...,год американский суд оккупировать германия суд...,3
145,Лабиринт Фавна,Испания 1944 года. Это история о маленькой дев...,25.08.2006,"детектив, драма, триллер, фэнтези",8.53/10,испания года это история о маленькой девочке о...,испания года история маленькой девочке офелии ...,испан год истор маленьк девочк офел жесток отч...,испания год история маленький девочка офелия ж...,3
148,Нечто,На самом холодном континенте планеты - Антаркт...,20.08.1982,"детектив, триллер, ужасы, фантастика",8.77/10,на самом холодном континенте планеты антарктид...,самом холодном континенте планеты антарктиде н...,сам холодн континент планет антарктид небольш ...,холодный континент планета антарктида небольшо...,3
151,Сокровища Сьерра Мадре,"Два бедных американца, прознав от престарелого...",29.04.1948,"боевик, вестерн, драма, приключения",8.77/10,два бедных американца прознав от престарелого ...,бедных американца прознав престарелого старате...,бедн американц прозна престарел старател золот...,бедный американец прознать престарелый старате...,3
153,Большой побег,Попавшие в плен к фашистам союзники разрабаты...,10.08.1963,"военный, драма, исторический, приключения",8.09/10,попавшие в плен к фашистам союзники разрабаты...,попавшие плен фашистам союзники разрабатывают ...,попа плен фашист союзник разрабатыва план побе...,попасть плен фашист союзник разрабатывать план...,3
158,Расемон,Древняя Япония. Расследуется дело об убийстве ...,25.08.1950,"драма, криминал",8.00/10,древняя япония расследуется дело об убийстве с...,древняя япония расследуется дело убийстве саму...,древн япон расслед дел убийств самур изнасилов...,древний япония расследоваться дело убийство са...,3
161,Китайский квартал,"Частный детектив, расследующий дело о супружес...",20.06.1974,"детектив, драма, криминал, триллер",8.45/10,частный детектив расследующий дело о супружеск...,частный детектив расследующий дело супружеской...,частн детект расслед дел супружеск неверн оказ...,частный детектив расследовать дело супружеский...,3
163,"Карты, деньги и два ствола",Четыре друга решили преумножить свое состояние...,28.08.1998,"криминал, триллер",8.66/10,четыре друга решили преумножить свое состояние...,четыре друга решили преумножить свое состояние...,четыр друг реш преумнож сво состоян игр карт о...,четыре друг решить преумножить состояние игра ...,3
165,Головоломка,Мультфильм расскажет о процессе формирования м...,17.06.2015,"драма, комедия, мультфильм, приключения, семей...",8.40/10,мультфильм расскажет о процессе формирования м...,мультфильм расскажет процессе формирования мыс...,мультфильм расскажет процесс формирован мысл г...,мультфильм рассказать процесс формирование мыс...,3
176,Гран Торино,"Клинт Иствуд играет ветерана Корейской войны, ...",22.01.2009,"боевик, драма, триллер",8.91/10,клинт иствуд играет ветерана корейской войны п...,клинт иствуд играет ветерана корейской войны п...,клинт иствуд игра ветера корейск войн противос...,клинт иствуд играть ветеран корейский война пр...,3
179,Мой сосед Тоторо,"Две девочки, приехавшие в сельскую местность, ...",16.04.1988,"аниме, мультфильм, приключения, семейный, фэнтези",8.52/10,две девочки приехавшие в сельскую местность чт...,две девочки приехавшие сельскую местность рядо...,две девочк приеха сельск местност ряд сво недо...,девочка приехать сельский местность рядом недо...,3
181,Дети небес,Али потерял туфли своей младшей сестры Захры. ...,22.04.1998,"драма, комедия",8.67/10,али потерял туфли своей младшей сестры захры д...,али потерял туфли своей младшей сестры захры д...,ал потеря туфл сво младш сестр захр дет настол...,али потерять туфля младший сестра захры ребёно...,3
187,"Отель ""Гранд Будапешт""",История о горестях и тревогах невозмутимого ко...,06.02.2014,"комедия, криминал, приключения",8.32/10,история о горестях и тревогах невозмутимого ко...,история горестях тревогах невозмутимого консье...,истор горест тревог невозмутим консьерж работа...,история горесть тревога невозмутимый консьерж ...,3
199,Челюсти,Гигантская белая акула вселяет ужас в жителей ...,07.07.1975,"триллер, ужасы",8.31/10,гигантская белая акула вселяет ужас в жителей ...,гигантская белая акула вселяет ужас жителей по...,гигантск бел акул вселя ужас жител популярн ку...,гигантский белый акула вселять ужас житель поп...,3
203,Мэри и Макс,Мульфильм рассказывает историю очень необычной...,09.04.2009,"драма, комедия, мультфильм",7.75/10,мульфильм рассказывает историю очень необычной...,мульфильм рассказывает историю очень необычной...,мульфильм рассказыва истор очен необычн дружб ...,мульфильм рассказывать история очень необычный...,3
204,Плата за страх,"В небольшом городе Латинской Америки, где проц...",22.04.1953,"драма, приключения, триллер",9.00/10,в небольшом городе латинской америки где процв...,небольшом городе латинской америки процветает ...,небольш город латинск америк процвета безработ...,небольшой город латинский америка процветать б...,3
206,Третий человек,"Прибыв в Вену, писатель Холли Мартине обнаруж...",31.08.1949,"детектив, нуар, триллер",7.25/10,прибыв в вену писатель холли мартине обнаружи...,прибыв вену писатель холли мартине обнаруживае...,приб вен писател холл мартин обнаружива пригла...,прибыть вена писатель холль мартин обнаруживат...,3
209,Токийская повесть,Пожилая супружеская пара из небольшого провинц...,03.11.1953,драма,8.50/10,пожилая супружеская пара из небольшого провинц...,пожилая супружеская пара небольшого провинциал...,пожил супружеск пар небольш провинциальн город...,пожилой супружеский пара небольшой провинциаль...,3
215,В центре внимания,"Реальная история, в основу которой легло рассл...",07.01.2016,"биографический, драма, исторический, триллер",8.07/10,реальная история в основу которой легло рассле...,реальная история основу которой легло расследо...,реальн истор основ котор легл расследован пров...,реальный история основа лечь расследование про...,3
218,Взвод,Молодой человек служит во Вьетнаме и переживае...,19.02.1987,"боевик, военный, драма",8.85/10,молодой человек служит во вьетнаме и переживае...,молодой человек служит вьетнаме переживает ужа...,молод человек служ вьетнам пережива ужас войн ...,молодой человек служить вьетнам переживать ужа...,3
221,Перед закатом,"Джесси, писатель из США, и Селин, француженка...",17.06.2004,"драма, мелодрама",8.00/10,джесси писатель из сша и селин француженка ра...,джесси писатель сша селин француженка работающ...,джесс писател сша селин француженк работа орга...,джесси писатель сша селина француженка работат...,3
224,Лучшие годы нашей жизни,Три ветерана Второй мировой войны возвращаютс...,21.11.1946,"военный, драма, мелодрама",8.50/10,три ветерана второй мировой войны возвращаютс...,ветерана второй мировой войны возвращаются дом...,ветера втор миров войн возвраща дом небольш ам...,ветеран второй мировой война возвращаться домо...,3
226,Гонка,Фильм основан на реальных событиях произошедши...,12.09.2013,"биографический, боевик, драма, спорт",8.45/10,фильм основан на реальных событиях произошедши...,основан реальных событиях произошедших году тр...,основа реальн событ произошедш год трасс форму...,основать реальный событие произойти год трасса...,3
231,Хатико: Самый верный друг,Фильм о великой преданности и замечательной др...,08.07.2009,"драма, семейный",8.71/10,фильм о великой преданности и замечательной др...,великой преданности замечательной дружбе снят ...,велик предан замечательн дружб снят одн истор ...,великий преданность замечательный дружба снято...,3
234,Служанка,Гениальный мошенник и искусная воровка объедин...,01.06.2016,"драма, мелодрама, эротика",7.62/10,гениальный мошенник и искусная воровка объедин...,гениальный мошенник искусная воровка объединяю...,гениальн мошенник искусн воровк объединя усил ...,гениальный мошенник искусный воровка объединят...,3
237,Битва за Алжир,Фильм о самой кровавой революции 19-го века.,08.09.1966,"военный, драма, исторический",7.60/10,фильм о самой кровавой революции го века,самой кровавой революции го века,сам кровав революц го век,кровавый революция го век,3
239,День сурка,Амбициозный телевизионный ведущий Фил Коннорс ...,12.02.1993,"комедия, мелодрама, фэнтези",8.97/10,амбициозный телевизионный ведущий фил коннорс ...,амбициозный телевизионный ведущий фил коннорс ...,амбициозн телевизион ведущ фил коннорс кажд го...,амбициозный телевизионный ведущий фил коннорс ...,3
243,Прислуга,60-е годы прошлого века. Америка. Юг.Фильм объ...,10.08.2011,драма,8.29/10,е годы прошлого века америка юг фильм объедин...,е годы прошлого века америка юг объединяет суд...,е год прошл век америк юг объединя судьб двух ...,год прошлое век америка юг объединять судьба ч...,3
246,"Париж, Техас",История уже не молодого человека по имени Трэв...,19.09.1984,драма,7.33/10,история уже не молодого человека по имени трэв...,история молодого человека имени трэвис потеряв...,истор молод человек имен трэвис потеря год аме...,история молодой человек имя трэвиснуть потерят...,3
247,Аладдин,В сказочном городе Аграба живет Аладдин - вор ...,30.04.1993,"комедия, мелодрама, мультфильм, мюзикл, приклю...",8.66/10,в сказочном городе аграба живет аладдин вор с ...,сказочном городе аграба живет аладдин вор добр...,сказочн город аграб живет аладдин вор добр сер...,сказочный город аграб жить аладдин вор добрый ...,3

In [41]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=100000990000000000000,
                                 min_df=0.01, stop_words=russian_stopwords,
                                 ngram_range=(1,3))
tfidf_matrix = tfidf_vectorizer.fit_transform(df[df['cluster']==3]['text_lemm'])
# создание модели LSA
lsa_model = TruncatedSVD(n_components=5, random_state=0)
lsa_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(lsa_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

# создание модели NMF
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(nmf_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: год, война, мировой война, второй, второй мировой война, второй мировой, мировой, американский, еврей, время
Topic 1: город, девочка, маленький девочка, полицейский, каждый, год, жить, маленький, день, найти
Topic 2: девочка, маленький, маленький девочка, голова, формирование мысль голова, мысль, голова маленький, мысль голова маленький, мысль голова, мультфильм
Topic 3: американский, год американский, год, имя, городок, молодой, молодой человек, городок париж, потерять год, имя трэвиснуть потерять
Topic 4: планета, война, делать, человек, ива, валл, кольцо, жить, молодой, молодой человек
Topic 0: второй, мировой, второй мировой война, второй мировой, мировой война, война, еврей, американский, время второй, время второй мировой
Topic 1: девочка, город, маленький, маленький девочка, жить, полицейский, офелия, рассказать, голова, ребёнок
Topic 2: день, век, каждый, го век, го, судьба, пёс, революция го, кровавый, кровавый революция
Topic 3: американский, год, год американский, история, молодой, молодой человек, имя, париж, история молодой человек, история молодой
Topic 4: планета, команда, схватка, рипнуть, инопланетный, учёный, акула, учёный вступать, вступать смертельный, континент

In [42]:
df[df['cluster']==4]

,title,description,release_date,tags,rating,prep_text,tokenize_text,text_stem,text_lemm,cluster
1,Крестный отец,"Фильм, ставший классикой своего жанра, рассказ...",24.03.1972,"драма, триллер",9.11/10,фильм ставший классикой своего жанра рассказыв...,ставший классикой своего жанра рассказывающий ...,ставш классик сво жанр рассказыва истор влияте...,стать классика жанр рассказывать история влият...,4
3,Крестный отец 2,Продолжение эпохальной саги режиссера Френсиса...,12.12.1974,"драма, криминал",8.88/10,продолжение эпохальной саги режиссера френсиса...,продолжение эпохальной саги режиссера френсиса...,продолжен эпохальн саг режиссер френсис форд к...,продолжение эпохальный сага режиссёр френсиса ...,4
18,Интерстеллар,Земля изживает себя и человечество должно иска...,06.11.2014,"детектив, приключения, фантастика",8.71/10,земля изживает себя и человечество должно иска...,земля изживает человечество должно искать новы...,земл изжива человечеств должн иска нов дом эт ...,земля изживать человечество должный искать нов...,4
28,Звездные войны: Эпизод 4 - Новая надежда,Принцесса Лейя - предводительница повстанцев з...,25.05.1977,"боевик, приключения, фантастика, фэнтези",8.92/10,принцесса лейя предводительница повстанцев зах...,принцесса лейя предводительница повстанцев зах...,принцесс лей предводительниц повстанц захвач з...,принцесса лейя предводительница повстанец захв...,4
32,Паразиты,Семья безработных не желает трудиться и живут ...,21.05.2019,"драма, комедия, триллер",8.28/10,семья безработных не желает трудиться и живут ...,семья безработных желает трудиться живут счет ...,сем безработн жела труд живут счет шантаж бога...,семья безработный желать трудиться жить счёт ш...,4
39,Американская история Х,"Дерек Виньярд вернулся из тюрьмы, чтобы найти ...",12.02.1999,"драма, криминал",8.58/10,дерек виньярд вернулся из тюрьмы чтобы найти с...,дерек виньярд вернулся тюрьмы найти своего мла...,дерек виньярд вернул тюрьм найт сво младш брат...,дерек виньярд вернуться тюрьма найти младший б...,4
40,Леон,Леон - профессиональный убийца. Он с легкостью...,14.09.1994,"боевик, драма, криминал, триллер",8.95/10,леон профессиональный убийца он с легкостью вы...,леон профессиональный убийца легкостью выполня...,леон профессиональн убийц легкост выполня сам ...,леон профессиональный убийца лёгкость выполнят...,4
47,1+1,Основанная на реальных событиях история необыч...,02.11.2011,"драма, комедия",8.99/10,основанная на реальных событиях история необыч...,основанная реальных событиях история необычной...,основа реальн событ истор необычн дружб двух с...,основать реальный событие история необычный др...,4
52,Однажды на Диком Западе,Не расстающийся со совей губной гармоникой таи...,21.12.1968,"вестерн, драма",8.48/10,не расстающийся со совей губной гармоникой таи...,расстающийся совей губной гармоникой таинствен...,расста сов губн гармоник таинствен бродяг изве...,расставаться советь губный гармоника таинствен...,4
53,Огни большого города,Маленький бродяга встречает на улице слепую цв...,27.02.1931,"драма, комедия, мелодрама",9.00/10,маленький бродяга встречает на улице слепую цв...,маленький бродяга встречает улице слепую цвето...,маленьк бродяг встреча улиц слеп цветочниц зад...,маленький бродяга встречать улица слепой цвето...,4
55,Апокалипсис сегодня,Самый разгар войны во Вьетнаме. Капитан Уиллар...,15.08.1979,"военный, драма",8.81/10,самый разгар войны во вьетнаме капитан уиллард...,самый разгар войны вьетнаме капитан уиллард ма...,сам разгар войн вьетнам капита уиллард мартин ...,самый разгар война вьетнам капитан уиллард мар...,4
59,12-я неудача,Фильм рассказывает реальную историю деревенско...,27.10.2023,"биографический, драма",7.00/10,фильм рассказывает реальную историю деревенско...,рассказывает реальную историю деревенского пар...,рассказыва реальн истор деревенск пар очен бед...,рассказывать реальный история деревенский пари...,4
60,Жизнь других,Ужасающая до смешного система слежек в Восточн...,23.03.2006,"драма, триллер",8.62/10,ужасающая до смешного система слежек в восточн...,ужасающая смешного система слежек восточной ев...,ужаса смешн систем слежек восточн европ нача х...,ужасающий смешной система слежка восточный евр...,4
64,Человек-паук: Через вселенные,Сюжет рассказывает о подростке из Нью-Йорка Ма...,12.12.2018,"боевик, кинокомикс, мультфильм, приключения, с...",8.10/10,сюжет рассказывает о подростке из нью йорка ма...,сюжет рассказывает подростке нью йорка майлзе ...,сюжет рассказыва подростк нью йорк майлз морал...,сюжет рассказывать подросток нью йорк майлз мо...,4
82,Джокер,"История о том, как Артур Флек, страдающий псих...",03.10.2019,"драма, кинокомикс, криминал, приключения, триллер",8.38/10,история о том как артур флек страдающий психич...,история артур флек страдающий психическим расс...,истор артур флек страда психическ расстройств ...,история артур флек страдать психический расстр...,4
90,Реквием по мечте,"Наркотики. Они забирают ум, тело и душу. Четыр...",03.11.2000,драма,8.62/10,наркотики они забирают ум тело и душу четыре ж...,наркотики забирают ум тело душу четыре жизни ч...,наркотик забира ум тел душ четыр жизн четыр не...,наркотик забирать ум тело душа четыре жизнь че...,4
97,Бешеные псы,"Шесть преступников, никогда в жизни личной и п...",25.06.1992,"драма, криминал, триллер",8.63/10,шесть преступников никогда в жизни личной и пр...,шесть преступников жизни личной профессиональн...,шест преступник жизн личн профессиональн перес...,шесть преступник жизнь личный профессиональный...,4
98,Лоуренс Аравийский,"Биографическая военная драма, рассказывающая о...",30.01.1963,"биографический, военный, драма, приключения",8.87/10,биографическая военная драма рассказывающая об...,биографическая военная драма рассказывающая од...,биографическ воен драм рассказыва одн наибол я...,биографический военный драма рассказывать наиб...,4
102,Оппенгеймер,"О чем фильм ""Оппенгеймер""? Это история жизни Р...",21.07.2023,"биографический, драма, исторический",8.20/10,о чем фильм оппенгеймер это история жизни робе...,оппенгеймер история жизни роберта оппенгеймера...,оппенгеймер истор жизн роберт оппенгеймер физи...,оппенгеймер история жизнь роберт оппенгеймер ф...,4
110,Амели,Необычная и красивая сказка про очаровательную...,25.04.2001,"драма, комедия, мелодрама",8.00/10,необычная и красивая сказка про очаровательную...,необычная красивая сказка очаровательную немно...,необычн красив сказк очаровательн немн стран д...,необычный красивый сказка очаровательный немно...,4
115,Афера,"1930-й год. Чикаго. Молодой мошенник, желающий...",25.12.1973,"драма, комедия, криминал",8.58/10,й год чикаго молодой мошенник желающий отомст...,й год чикаго молодой мошенник желающий отомсти...,й год чикаг молод мошенник жела отомст кримина...,й год чикаго молодой мошенник желать отомстить...,4
121,1917,Фильм рассказывает об ужасах Первой мировой во...,04.12.2019,"военный, драма, исторический",8.16/10,фильм рассказывает об ужасах первой мировой во...,рассказывает ужасах первой мировой войны котор...,рассказыва ужас перв миров войн котор испытыва...,рассказывать ужас первый мировой война испытыв...,4
124,Гамильтон,Современная бродвейская постановка рассказывае...,03.07.2020,"биографический, драма, исторический, мюзикл",9.00/10,современная бродвейская постановка рассказывае...,современная бродвейская постановка рассказывае...,современ бродвейск постановк рассказыва жизн о...,современный бродвейский постановка рассказыват...,4
130,Волк с Уолл-стрит,Фильм рассказывает о криминальном прошлом фина...,25.12.2013,"биографический, драма, комедия, криминал",8.26/10,фильм рассказывает о криминальном прошлом фина...,рассказывает криминальном прошлом финансиста д...,рассказыва криминальн прошл финансист джорда б...,рассказывать криминальный прошлый финансист дж...,4
132,В джазе только девушки,"Два бедных чикагских музыканта, чтобы получить...",29.03.1959,"комедия, криминал, мелодрама, музыка, приключения",8.73/10,два бедных чикагских музыканта чтобы получить ...,бедных чикагских музыканта получить выгодную р...,бедн чикагск музыкант получ выгодн работ заодн...,бедный чикагский музыкант получить выгодный ра...,4
139,Нефть,Фильм снят по знаменитому роману Эптона Синкле...,11.01.2008,"драма, триллер",8.35/10,фильм снят по знаменитому роману эптона синкле...,снят знаменитому роману эптона синклера лауреа...,снят знаменит роман эптон синклер лауреат пули...,снятой знаменитый роман эптон синклер лауреат ...,4
140,Парк Юрского периода,Ученые смогли возродить доисторических динозав...,13.06.1993,"боевик, приключения, фантастика",8.94/10,ученые смогли возродить доисторических динозав...,ученые смогли возродить доисторических динозав...,учен смогл возрод доисторическ динозавр исполь...,учёный смочь возродить доисторический динозавр...,4
142,Казино,С Сэмом Ротстином по кличке Ас сравнится не мо...,20.01.1996,"драма, исторический, криминал, триллер",8.81/10,с сэмом ротстином по кличке ас сравнится не мо...,сэмом ротстином кличке ас сравнится мог никто ...,сэм ротстин кличк ас сравн мог никт сам процве...,сэм ротстин кличка ас сравниться мочь никто са...,4
144,Шестое чувство,Восьмилетний мальчик Коул постоянно видит мерт...,06.08.1999,"детектив, драма, мистика, триллер",8.52/10,восьмилетний мальчик коул постоянно видит мерт...,восьмилетний мальчик коул постоянно видит мерт...,восьмилетн мальчик коул постоя вид мертв люд р...,восьмилетний мальчик коул постоянно видеть мёр...,4
170,Мост через реку Квай,Уладив «разногласия» с командиром японского ла...,02.10.1957,"военный, драма, приключения",8.43/10,уладив разногласия с командиром японского лаге...,уладив разногласия командиром японского лагеря...,улад разноглас командир японск лагер военнопле...,уладить разногласие командир японский лагерь в...,4
175,Человек-Паук 3: Нет пути домой,"Продолжение истории о Питере Паркере - юноше, ...",16.12.2021,"боевик, кинокомикс, приключения, фантастика",7.93/10,продолжение истории о питере паркере юноше слу...,продолжение истории питере паркере юноше случа...,продолжен истор питер паркер юнош случайн став...,продолжение история питер паркер юноша случайн...,4
188,По соображениям совести,"Военная драма, рассказывающая историю Десмонда...",04.11.2016,"биографический, военный, драма, мелодрама",8.52/10,военная драма рассказывающая историю десмонда ...,военная драма рассказывающая историю десмонда ...,воен драм рассказыва истор десмонд досс рядов ...,военный драма рассказывать история десмонд дос...,4
195,Дикие истории,Фильм состоит из нескольких историй об оказавш...,21.08.2014,"драма, криминал, триллер",8.24/10,фильм состоит из нескольких историй об оказавш...,состоит нескольких историй оказавшихся месте в...,состо нескольк истор оказа мест врем люд,состоять несколько история оказаться место вре...,4
197,Паровоз Генерал,У Джонни в жизни есть две любви - его женщина ...,31.12.1926,"боевик, военный, комедия, мелодрама, приключения",9.00/10,у джонни в жизни есть две любви его женщина ан...,джонни жизни две любви женщина аннабель парово...,джон жизн две любв женщин аннабел паровоз гене...,джонни жизнь любовь женщина аннабель паровоз г...,4
200,Рататуй,Реми - это необыкновенный и весьма симпатичный...,28.06.2007,"детский, комедия, мультфильм, семейный",8.54/10,реми это необыкновенный и весьма симпатичный к...,реми необыкновенный весьма симпатичный крыс фе...,рем необыкновен весьм симпатичн крыс феноменал...,реми необыкновенный весьма симпатичный крыса ф...,4
205,Земляничная поляна,Профессор Борг из Стокгольма едет на вручение ...,06.10.1958,драма,8.80/10,профессор борг из стокгольма едет на вручение ...,профессор борг стокгольма едет вручение почетн...,профессор борг стокгольм едет вручен почетн до...,профессор борг стокгольм ехать вручение почётн...,4
207,Ford против Ferrari,Фильм рассказывает реальную историю противосто...,14.11.2019,"биографический, боевик, драма, спорт",8.48/10,фильм рассказывает реальную историю противосто...,рассказывает реальную историю противостояния а...,рассказыва реальн истор противостоян автоконце...,рассказывать реальный история противостояние а...,4
223,Да прольется свет,Когда мужчину из беднейшего племени арестовыва...,01.11.2021,"детектив, драма, криминал",7.00/10,когда мужчину из беднейшего племени арестовыва...,мужчину беднейшего племени арестовывают кражу ...,мужчин бедн племен арестовыва краж жен раздумы...,мужчина бедный племя арестовывать кража жена р...,4
225,Изгоняющий дьявола,В 12-летнюю девочку вселился дьявол. Врачи бес...,26.12.1973,"драма, триллер, ужасы",8.50/10,в летнюю девочку вселился дьявол врачи бессиль...,летнюю девочку вселился дьявол врачи бессильны...,летн девочк всел дьявол врач бессильн либ сдел...,летний девочка вселиться дьявол врач бессильны...,4
235,Быть или не быть,В оккупированной нацистами Польше актерская тр...,02.05.1942,"военный, комедия",10.00/10,в оккупированной нацистами польше актерская тр...,оккупированной нацистами польше актерская труп...,оккупирова нацист польш актерск трупп оказыва ...,оккупировать нацист польша актёрский труппа ок...,4
240,Стальной гигант,"История о том, как 9ти-летний мальчик подружил...",06.08.1999,"драма, мультфильм, семейный, фантастика",8.73/10,история о том как ти летний мальчик подружился...,история ти летний мальчик подружился роботом к...,истор ти летн мальчик подруж робот космос амер...,история ти летний мальчик подружиться робот ко...,4

In [43]:
tfidf_vectorizer = TfidfVectorizer(max_df=0.8, max_features=100000990000000000000,
                                 min_df=0.01, stop_words=russian_stopwords,
                                 ngram_range=(1,3))
tfidf_matrix = tfidf_vectorizer.fit_transform(df[df['cluster']==1]['text_lemm'])
# создание модели LSA
lsa_model = TruncatedSVD(n_components=5, random_state=0)
lsa_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(lsa_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

# создание модели NMF
nmf_model = NMF(n_components=5, random_state=0)
nmf_model.fit(tfidf_matrix)

# вывод топ слов для каждой темы
for i, topic in enumerate(nmf_model.components_):
    print(f"Topic {i}: {', '.join([tfidf_vectorizer.get_feature_names_out()[i] for i in topic.argsort()[:-11:-1]])}")

Topic 0: жизнь, человек, жена, история, обычный, работа, миллион, ребёнок, друг, совершенно
Topic 1: работа, го, го век, век, агент, рикки, рабство, меррик, джозеф, принять
Topic 2: жена, рабство, джанго, становиться, зритель, век, го, го век, доктор, находиться
Topic 3: жена, стать, мужчина, лицо, заветный мечта, реальность конец жизнь, мультфильм заветный, мультфильм, мультфильм заветный мечта, заветный мечта приключение
Topic 4: становиться, ночь, мэрион, отец, пока, мир, обычный, тысяча, ребёнок, весь
Topic 0: друг, человек, обычный, жизнь, пока, игрушка, приключение, остаться, марти, отец
Topic 1: полицейский, работа, грабитель, костелло, принять, анджелес, лос анджелес, лос, фрэнк, работать
Topic 2: жена, рабство, джанго, жестокий, становиться, уходить, леонард, предложение, бывший, пытаться
Topic 3: нью йорк, нью, мочь, йорк, взрыв, доллар, история, человек, миллион доллар, год
Topic 4: жизнь, семья, младший, младший брат, брат, мальчик, следить, воспоминание, помогать, однажды

In [44]:
pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

## Классификация

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['tokenize_text'], df['cluster'], 
                                                      test_size=0.3, 
                                                      random_state=0)

In [46]:
len(X_train)

174

In [47]:
len(X_test)

75

In [48]:
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

In [49]:
vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1,3), stop_words=russian_stopwords)
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

## LogisticRegression

In [50]:
model_lr = LogisticRegression()
model_lr.fit(X_train_tfidf, y_train)

LogisticRegression()

In [51]:
y_pred = model_lr.predict(X_test_tfidf)

In [52]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00        16
           2       0.33      0.95      0.49        20
           3       0.44      0.47      0.46        17
           4       0.00      0.00      0.00        12

    accuracy                           0.36        75
   macro avg       0.16      0.28      0.19        75
weighted avg       0.19      0.36      0.24        75

In [53]:
X_test_tfidf.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
y_pred

array([2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 3, 2, 3, 2, 2, 3,
       3, 2, 2, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2,
       2, 2, 2, 3, 2, 2, 2, 2, 2], dtype=int64)

## RandomForestClassifier

In [55]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train_tfidf, y_train)

RandomForestClassifier()

In [56]:
y_pred = model_rf.predict(X_test_tfidf)

In [57]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.00      0.00      0.00        16
           2       0.29      0.80      0.42        20
           3       0.35      0.35      0.35        17
           4       0.00      0.00      0.00        12

    accuracy                           0.29        75
   macro avg       0.13      0.23      0.15        75
weighted avg       0.16      0.29      0.19        75

## KNeighborsClassifier

In [58]:
model_knn = KNeighborsClassifier()
model_knn.fit(X_train_tfidf, y_train)

KNeighborsClassifier()

In [59]:
y_pred = model_knn.predict(X_test_tfidf)

In [60]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.18      0.30      0.22        10
           1       0.36      0.25      0.30        16
           2       0.34      0.50      0.41        20
           3       0.45      0.29      0.36        17
           4       0.29      0.17      0.21        12

    accuracy                           0.32        75
   macro avg       0.33      0.30      0.30        75
weighted avg       0.34      0.32      0.32        75

## Сохранение модели

In [61]:
import pickle

with open('film_model.pkl', 'wb') as f:
    pickle.dump(model_knn, f)

In [62]:
with open('film_vectorizer.pkl', 'wb') as f:
    pickle.dump(vectorizer, f)

In [63]:
df.to_csv('data_movies.csv')

In [64]:
t1 = "Бухгалтер Энди Дюфрейн обвинён в убийстве собственной жены и её любовника. Оказавшись в тюрьме под названием Шоушенк; он сталкивается с жестокостью и беззаконием; царящими по обе стороны решётки. Каждый; кто попадает в эти стены; становится их рабом до конца жизни. Но Энди; обладающий живым умом и доброй душой; находит подход как к заключённым; так и к охранникам; добиваясь их особого к себе расположения."

In [65]:
with open('film_model.pkl', 'rb') as file:
    model = pickle.load(file)

with open('film_vectorizer.pkl', 'rb') as file:
    vectorizer = pickle.load(file)

In [66]:
def fun_punctuation_text(text):
    text = text.lower()
    text = ''.join([ch for ch in text if ch not in string.punctuation])
    text = ''.join([i if not i.isdigit() else '' for i in text])
    text = ''.join([i if i.isalpha() else ' ' for i in text])
    text = re.sub(r'\s+', ' ', text, flags=re.I)
    text = re.sub('[a-z]', '', text, flags=re.I)
    st = '❯\xa0'
    text = ''.join([ch if ch not in st else ' ' for ch in text])
    return text

In [67]:
def fun_lemmatizing_text(text):
    tokens = word_tokenize(text)
    res = list()
    for word in tokens:
        p = pymorphy3.MorphAnalyzer(lang='ru').parse(word)[0]
        res.append(p.normal_form)  
    text = " ".join(res)
    return text

In [68]:
def fun_tokenize(text):
    t = word_tokenize(text)
    tokens = [token for token in t if token not in russian_stopwords]
    text = " ".join(tokens)
    return text

In [ ]:
t1 = fun_tokenize(fun_lemmatizing_text(fun_punctuation_text(t1)))

In [ ]:
text_vectorized = vectorizer.transform([t1])

In [ ]:
text_vectorized.toarray()

In [ ]:
prediction = model.predict(text_vectorized)  
probabilities = model.predict_proba(text_vectorized)

In [ ]:
print(f"Класс: {prediction[0]}")
print(f"Вероятности: {probabilities}")

In [ ]:
t2 = "Влиятельный гангстер из Лондона решает продать свой бизнес по справедливой цене. Но не все в его сфере уважают справедливость. Бандиты из разных частей света начинают охоту на «стареющего льва». Британский король криминального жанра, культовый режиссер Гай Ричи представляет лихо закрученную, ироничную и неполиткорректную гангстерскую комедию в лучших традициях своего стиля и юмора. Колоритных и опасных «джентльменов» сыграли Мэттью МакКонахи, Чарли Ханнэм, Хью Грант и Колин Фаррелл, каким вы его еще не видели. Амбициозный кинодраматург (а вообще-то – беспринципный шантажист и скользкий частный сыщик) Флетчер рассказывает сюжет своего будущего фильма на основе реальных событий. Это история большого человека по имени Микки Пирсон, который с нуля создал многомиллионный бизнес по выращиванию и сбору нелегального «урожая». Когда его лихая молодость осталась позади, он решил стать примерным семьянином, передав дела надежному человеку. Желающих более чем достаточно, но появляется камень преткновения – цена. А также – принципиальность Пирсона, не идущего на уступки. Враги и предатели за его спиной начинают плести интриги, его правая рука Реймонд пытается держать оборону, а тем временем пронырливый наблюдатель Флетчер собирает компромат. Но даже он не видит всей картины и не подозревает, какая готовится кульминация."

In [ ]:
t2 = fun_tokenize(fun_lemmatizing_text(fun_punctuation_text(t2)))

In [ ]:
text_vectorized = vectorizer.transform([t2])

In [ ]:
text_vectorized.toarray()

In [ ]:
prediction = model.predict(text_vectorized)  
probabilities = model.predict_proba(text_vectorized)

In [ ]:
print(f"Класс: {prediction[0]}")
print(f"Вероятности: {probabilities}")