In [1]:
import pymupdf
import pandas as pd
import io
import glob

In [2]:
all_pdf = glob.glob(r"PDF2\*.pdf")

In [3]:
all_pdf

['PDF2\\Cocoapods, Carthage, SPM как выбрать менеджер зависимостей в iOS.pdf',
 'PDF2\\Deutsche Telekom и Perplexity объявили о новом «AI Phone» стоимостью менее 1 000 долларов _ Хабр.pdf',
 'PDF2\\imgonline-com-ua-site2pdfB28eKGLy6EjA.pdf',
 'PDF2\\OSINT & Hacking — как работает фишинг для нельзяграма _ Хабр3.pdf',
 'PDF2\\Yandex N.V. запретили в\xa0течение пяти лет создавать аналогичные «Яндексу» сервисы _ Хабр.pdf',
 'PDF2\\Быстрое начало работы с Gitlab CICD.pdf',
 'PDF2\\Генеральный директор Mozilla покинула свой пост _ Хабр.pdf',
 'PDF2\\За что безопасники будут гореть в аду_ _ Хабр.pdf',
 'PDF2\\Заезжаем в Kotlin Multiplatform. Но какой ценой_ _ Хабр.pdf',
 'PDF2\\ИИ-агенты в Альфа-Банке_ нейросети создают автотесты без участия человека _ Хабр.pdf',
 'PDF2\\Инструменты наблюдаемости, о которых нужно знать в 2023 году.pdf',
 'PDF2\\История российской науки_ напишем вместе_ _ Хабр.pdf',
 'PDF2\\Как системному аналитику написать хорошее резюме —\xa011 рекомендаций _ Хабр.pdf',
 'PDF2\\Как создать аппаратный эмулятор CD-ROM без паяльника _ Хабр.pdf',
 'PDF2\\Как создать аппаратный эмулятор CD-ROM.pdf',
 'PDF2\\Компании _ Хабр.pdf',
 'PDF2\\Компании.pdf',
 'PDF2\\Может ли chatGPT забронировать столик в ресторане через WhatsApp.pdf',
 'PDF2\\Новые утечки.pdf',
 'PDF2\\Почему Data Science не для вас.pdf']

In [7]:
first_pdf_document = r"PDF2\imgonline-com-ua-site2pdfB28eKGLy6EjA.pdf"
doc1 = pymupdf.open(first_pdf_document)
print("Исходный документ: ", doc1)
print("\nКоличество страниц: %i\n\n------------------\n\n" % doc1.page_count)
print(doc1.metadata)
for current_page in range(len(doc1)):
    page = doc1.load_page(current_page)
    page_text = page.get_text("text")
    print("Стр. ", current_page+1, "\n")
    print(page_text)

Исходный документ:  Document('PDF2\imgonline-com-ua-site2pdfB28eKGLy6EjA.pdf')

Количество страниц: 21

------------------


{'format': 'PDF 1.4', 'title': 'OSINT & Hacking — как работает фишинг для нельзяграма / Хабр', 'author': '', 'subject': '', 'keywords': '', 'creator': 'www.imgonline.com.ua/website-to-pdf.php', 'producer': '', 'creationDate': '', 'modDate': '', 'trapped': '', 'encryption': None}
Стр.  1

71.07
Рейтинг
Cloud4Y
#1 Корпоративный облачный провайдер
Автор оригинала: Yashwant Singh
Взлом Instagram*‑аккаунта — популярный запрос в поисковиках. Поэтому есть смысл рассказать
о том, как это обычно работает. Просто для того, чтобы вы знали, откуда может пойти атака.
 Cloud4Y 5 часов назад
OSINT & Hacking — как работает фишинг для нельзяграма
 Простой
 3 мин
 1.1K
Блог компании Cloud4Y , Информационная безопасность *, Социальные сети и сообщества
Обзор
 Перевод
КАК СТАТЬ АВТОРОМ

Стр.  2

Чтобы начать попытки заполучить доступ к аккаунту, вы должны знать ник человека, которого вы
пытаетесь взломать. Так что небольшая разведка будет очень кстати. Только не увлекайтесь.
Существуют различные инструменты для разведки, в первую очередь, поиск пользователя
в конкретной соцсети с целью узнать его ник. Я нашёл отличный инструмент под названием
«Slash», который можно использовать для поиска любых учётных записей пользователя, если он
везде регистрируется под одним ником.
Ставим Slash

Стр.  3

git clone https://github.com/theahmadov/slash
cd slash
pip install -r requirements.txt
python slash.py help
Я проверил Slash на себе, и посмотрите на эти результаты. Некоторые из учетных записей,
перечисленных здесь, были созданы много лет назад.

Стр.  4

Slash — это простой консольный инструмент. Но вы также можете использовать такие
инструменты, как WhatsMyName Web, который совершенно бесплатен.
Вот, посмотрите. Я проверил WhatsMyName на себе. Мой ник «earthtoyash».

Стр.  5

Теперь, когда мы знаем больше о нашем пользователе, можно использовать эти знания.

Стр.  6

Например, через отправку фишинговых ссылок. Для этого создадим полезную нагрузку с помощью
Zphisher.
Ставим Zphisher с GitHub
Клонируем репозиторий:
git clone --depth=1 https://github.com/htr-tech/zphisher.git
Запускаем файл zphisher.sh:
cd zphisher && ./zphisher.sh
При первом запуске он установит зависимости и на этом всё. Система скажет, что Zphisher
установлен. После установки вам нужно будет снова запустить zphisher.sh в каталоге zphisher
командой ./zphisher , и тогда вы получите что-то вроде этого:

Стр.  7

Как вы можете видеть, есть много вариантов и шаблонов, благодаря чему любой может
заниматься фишингом. Мы сосредоточимся на нельзяграме. Итак, введите «2» и нажмите Enter.

Стр.  8

Следующий шаг полностью зависит от вас, выберите любой из них.
Затем появится окно с выбором. Я выбрал третий вариант, так как он минималистичный и удобен
для того, чтобы показать возможности инструмента.

Стр.  9

Опять же, чтобы все было просто, я пропущу пользовательский порт, но если вы уже используете
порт 8080, то можете изменить его на 8000. Если нет, оставляйте всё как есть. Также важно
маскировать URL, ну просто в целях безопасности. Можно использовать что‑то вроде этого:

Стр.  10

Всё, Zphisher создал фишинговую ссылку, которую можно отправить жертве. Как только она
нажмёт на ссылку, вы начнёте получать информацию о ней. Например, IP‑адреса, имена
пользователей, пароли и т. д. Ещё можно использовать обратный поиск IP, чтобы определить
местоположение вашей цели и многое другое.
Итак, вот эти фишинговые ссылки.

Стр.  11

При нажатии открывается страница, похожая на официальную страницу входа в запрещённую
соцсеть.

Стр.  12

Вот она, нехорошая
После ввода учётных данных можно получить много информации на «хакерской» стороне
терминала.

Стр.  13

Вот так, господа и дамы, можно без особого труда взломать учетную запись в нельзяграме.
Поэтому в очередной раз напоминаем: нельзя нажимать на ссылки, которым вы не доверяете.
Само собой разумеется, не используйте информацию из этой статьи с намерением причинить
кому-либо вред. OSINT законен, но фишинг и кража личных данных даже в запрещённой соцсети
является уголовным преступлением. И да, * Организация Meta, а также её продукт Instagram, на
которые мы ссылаемся в этой статье, признаны экстремистскими и запрещены на территории РФ.
Спасибо за внимание!

Стр.  14

Cloud4Y
#1 Корпоративный облачный провайдер
Сайт
Facebook
Twitter
ВКонтакте
Telegram
Что ещё интересного есть в блоге Cloud4Y
→ Информационная безопасность и глупость: необычные примеры
→ NAS за шапку сухарей
→ Взлом Hyundai Tucson, часть 1, часть 2
→ Столетний язык программирования — какой он
→ 50 самых интересных клавиатур из частной коллекции
Теги:  взлом, соцсети, osint
Хабы:  Блог компании Cloud4Y, Информационная безопасность,
Социальные сети и
сообщества
 0
 19
 1

Стр.  15


Стр.  16

149
Карма
53.5
Рейтинг
Cloud4Y @Cloud4Y
Корпоративный облачный провайдер
Сайт
ВКонтакте
Telegram
 Комментарии 1
Публикации
ЛУЧШИЕ ЗА СУТКИ
ПОХОЖИЕ

Стр.  17


Стр.  18


Стр.  19

 ·
 ·
 ·
 ·
 ·
 ·
 ·
 ·
 ·
 ·
И Н Ф О Р М А Ц И Я
Сайт
www.cloud4y.ru

Стр.  20

Ваш аккаунт
Войти
Регистрация
Разделы
Публикации
Новости
Хабы
Компании
Авторы
Песочница
Дата регистрации
29 июля 2011
Дата основания
2009
Численность
51–100 человек
Местоположение
Россия
Представитель

Стр.  21

Информация
Устройство сайта
Для авторов
Для компаний
Документы
Соглашение
Конфиденциальность
Услуги
Корпоративный блог
Медийная реклама
Нативные проекты
Образовательные программы
Стартапам
Мегапроекты
Настройка языка
Техническая поддержка Вернуться на старую версию
© 2006–2023, Habr

In [8]:
second_pdf_document = r"PDF2\ИИ-агенты в Альфа-Банке_ нейросети создают автотесты без участия человека _ Хабр.pdf"
doc2 = pymupdf.open(second_pdf_document)
print("Исходный документ: ", doc2)
text = []
for current_page in range(len(doc2)):
    page = doc2.load_page(current_page)
    page_text = page.get_text("text")
    text.append(page_text)
    print(page_text)

Исходный документ:  Document('PDF2\ИИ-агенты в Альфа-Банке_ нейросети создают автотесты без участия человека _ Хабр.pdf')
404.32
Рейтинг
Альфа-Банк
Лучший мобильный банк по версии Markswebb
Подписаться
В Альфа-Банке мы внедрили ИИ-агентов, которые проектируют, разрабатывают и проверяют
автотесты. При этом полностью автономно, как QA-инженеры, но в разы быстрее и точнее.
Подобных примеров, когда ИИ разрабатывает автотесты от анализа требований до пул-реквеста,
в нашей стране, пожалуй, ещё не было.
Что умеют агенты?
Анализировать контекст из Jira и Confluence, вычленяя суть задачи.
Прогнозировать риски, зависимости и даже «пограничные» сценарии.
Генерировать DTO для REST API и превращать ручные сценарии в Java-тесты за минуты.
Сверять код с бизнес-логикой и техстандартами Альфы, защищая прод от случайных
ошибок.
Создавать вариативные проверки — от позитивных кейсов до сложных негативных условий.
Автоматизировать рутину.
В ИИ-команде QA есть несколько агентов, каждый работает над своей частью из перечная выше.
Сейчас решение пилотируется в нескольких продуктовых командах, но результаты уже видны:
AlfaTeam 2 часа назад
ИИ-агенты в Альфа-Банке: нейросети создают автотесты без
участия человека
1 мин
717
Блог компании Альфа-Банк, Искусственный интеллект, Тестирование IT-систем*
Войти
Моя
лента
Все
потоки Разработка Администрирование Дизайн Менеджмент Маркетинг Научпоп
КАК СТАТЬ АВТОРОМ
Зарплаты айтишников
Миграция за ночь? Легко! Без сна и с адре…

Альфа-Банк
Лучший мобильный банк по версии Markswebb
Сайт
Хабр Карьера
14
Карма
0.3
Рейтинг
@AlfaTeam
Пользователь
Сайт
Facebook
ВКонтакте
Другие новости
mefdayy 19 минут назад
Nvidia и Broadcom тестируют передовой процесс производства чипов
Intel
2 мин
меньше ошибок в проде, предсказуемые дедлайны и высвобожденные ресурсы для творческих
задач.
«Одна команда ИИ-агентов экономит десятки часов работы, увеличивает скорость релизов и
находит на 30% больше багов»
Святослав Соловьев, Директор по генеративному ИИ в ИТ Альфа-Банка.
В ближайшее время подробнее опишем как устроены агенты, какие технологии используем и как
мы измеряем их эффективность.
Теги: автоматизация, искусственный интеллект, тестирование, автотесты
Хабы: Блог компании Альфа-Банк, Искусственный интеллект, Тестирование IT-систем
Редакторский дайджест
Присылаем лучшие статьи раз в месяц
Электропочта
Комментарии 11
123
Подписаться

In [9]:
third_pdf_document = r"PDF2\Компании _ Хабр.pdf"
doc3 = pymupdf.open(third_pdf_document)
print("Исходный документ: ", doc3)
text = []
for current_page in range(len(doc3)):
    page = doc3.load_page(current_page)
    page_text = page.get_text("text")
    text.append(page_text)
    print(page_text)

Исходный документ:  Document('PDF2\Компании _ Хабр.pdf')
Все потоки
Добавить компанию
RUVDS.com
VDS/VPS-хостинг. Скидка 15% по коду HABR15
Пишет в хабы:  Читальный зал, DIY или Сделай сам, Научно-популярное, Электроника для начинающих,
Системное администрирование
2394.92
72K
Selectel
IT-инфраструктура для бизнеса
Пишет в хабы:  Компьютерное железо, Гаджеты, IT-инфраструктура, IT-компании,
Производство и разработка электроники
1935.27
40K
Timeweb Cloud
Облачная платформа для разработчиков и бизнеса
Пишет в хабы:  Читальный зал, Научно-популярное, JavaScript, DIY или Сделай сам, История IT
1538.54
1.1K
OTUS
Цифровые навыки от ведущих экспертов
Пишет в хабы:  Программирование, Java, Машинное обучение, Тестирование веб-сервисов, Python
830.05
103K
Яндекс
Как мы делаем Яндекс
Пишет в хабы:  Машинное обучение, Open source, Высокая производительность, Программирование,
Интерфейсы
721.54
164K
Open Data Science
Крупнейшее русскоязычное Data Science сообщество
Пишет в хабы:  Машинное обучение, Искусственный интеллект, Natural Language Processing, Open source,
Big Data
СТАТЬИ +63
НОВОСТИ +51
ХАБЫ
АВТОРЫ
КОМПАНИИ
Поиск
Название
Рейтинг
Подписчики
КАК СТАТЬ АВТОРОМ
Исследуем Духов Машин в новом Сезоне на Хабре

610.1
9.6K
ГК ЛАНИТ
Ведущая многопрофильная группа ИТ-компаний в РФ
Пишет в хабы:  Управление проектами, Карьера в IT-индустрии, Управление персоналом,
Машинное обучение, Программирование
569.92
54K
VK
Технологии, которые объединяют
Пишет в хабы:  Big Data, Машинное обучение, DevOps, Tarantool, Облачные сервисы
536.94
167K
getmatch
Рассказываем о том, как строить карьеру в IT
Пишет в хабы:  Карьера в IT-индустрии, Лайфхаки для гиков, Читальный зал, IT-эмиграция, Урбанизм
436.91
953
Wiren Board
Оборудование для автоматизации и мониторинга
Пишет в хабы:  Умный дом, Интернет вещей, Инженерные системы, DIY или Сделай сам,
Компьютерное железо
411.66
353
FirstVDS
Виртуальные и выделенные серверы в ДЦ в Москве
Пишет в хабы:  Научно-популярное, Системное администрирование, Читальный зал,
Информационная безопасность, IT-инфраструктура
398.02
24K
Конференции Олега Бунина (Онтико)
Профессиональные конференции для IT-разработчиков
Пишет в хабы:  Управление разработкой, Конференции, DevOps, Управление проектами,
Карьера в IT-индустрии
360.51
58K
AGIMA
Крупнейший интегратор digital-решений
Пишет в хабы:  Карьера в IT-индустрии, Управление проектами, Конференции, Управление персоналом,
Управление продуктом
336.45
519
Альфа-Банк
Лучший мобильный банк по версии Markswebb
Пишет в хабы:  Конференции, Анализ и проектирование систем, Машинное обучение, JavaScript,
Карьера в IT-индустрии

311.59
24K
Postgres Professional
Разработчик СУБД Postgres Pro
Пишет в хабы:  PostgreSQL, SQL, Администрирование баз данных, Open source, Хранение данных
305.42
76K
Ozon Tech
Стремимся делать лучший e-commerce в России
Пишет в хабы:  Конференции, Высокая производительность, Go, Тестирование веб-сервисов,
Программирование
282.75
28K
TINKOFF
IT’s Tinkoff — просто о сложном
Пишет в хабы:  Разработка под Android, Машинное обучение, Тестирование IT-систем,
Разработка мобильных приложений, Open source
282.47
40K
Хабр Карьера
Помогаем строить карьеру в IT
Пишет в хабы:  Карьера в IT-индустрии, Управление персоналом, Исследования и прогнозы в IT,
Блог компании Хабр, Финансы в IT
280.35
14K
JUG Ru Group
Конференции для Senior-разработчиков
Пишет в хабы:  Конференции, Java, Тестирование IT-систем, Разработка мобильных приложений, JavaScript
276.72
41K
Southbridge
Обеспечиваем стабильную работу highload-проектов
Пишет в хабы:  IT-инфраструктура, DevOps, Системное администрирование, Карьера в IT-индустрии,
Программирование
273.3
47K
1
2
3
... 16
17
ФИЛЬТР
Все
323
Веб-разработка
98
Программное обеспечение
180

Аппаратное обеспечение
40
Дизайн и юзабилити
22
Реклама и маркетинг
9
СМИ
5
Консалтинг и поддержка
49
Рекрутинг и HR
9
Электронная коммерция
41
Некоммерческие организации
5
Оптимизация
9
Производство мультимедиа-контента
9
Связь и телекоммуникации
54
Домены и хостинг
17
Поисковые технологии
9
Мобильные технологии
72
Веб-сервисы
97
Игры и развлечения
11
Информационная безопасность
47
Ваш аккаунт
Войти
Регистрация
Разделы
Публикации
Новости
Хабы
Компании
Авторы
Песочница
Информация
Устройство сайта
Для авторов
Для компаний
Документы
Соглашение
Конфиденциальность
Услуги
Корпоративный блог
Медийная реклама
Нативные проекты
Образовательные
программы
Стартапам
Мегапроекты

Настройка языка
Техническая поддержка
Вернуться на старую версию
© 2006–2023, Habr

In [15]:
def extract_text_from_pdf(pdf):
    doc = pymupdf.open(pdf)
    text = ''
    for current_page in range(len(doc)):
        page = doc.load_page(current_page)
        page_text = page.get_text("text")
        text += '\n' + page_text
    return text

In [17]:
all_names = []
all_descriptions = []
all_hubs = []
all_ratings = []
all_subscribers = []

def pars_pdf(text):
    text2 = text.split('\n')
    print(text2)
    for i in range(len(text2)-1, 0, -1):
        if text2[i] in ['Все потоки', 'Добавить компанию', 'НОВОСТИ', '+50','СТАТЬИ +64','СТАТЬИ', '+64', 'СТАТЬИ +63','НОВОСТИ +51','ХАБЫ','АВТОРЫ','КОМПАНИИ','Поиск','Название ','Рейтинг ','Подписчики','КАК СТАТЬ АВТОРОМ','Исследуем Духов Машин в новом Сезоне на Хабре'] or text2[i] == '':
            text2.pop(i)
    for i in range(len(text2)-1, 0, -1):
        if text2[i].__contains__('Пишет в хабы:'):
            hubs = text2[i]
            if (text2[i+1].isnumeric() or text2[i+1].__contains__(".")) and (text2[i+2].__contains__("K") or text2[i+2].isdecimal()):
                raiting = text2[i+1]
                subscribers = text2[i+2]
            elif (text2[i+2].isnumeric() or text2[i+2].__contains__(".")) and (text2[i+3].__contains__("K") or text2[i+3].isdecimal()):
                hubs += text2[i+1]
                raiting = text2[i+2]
                subscribers = text2[i+3]
            else:
                for j in text2[i+2]:
                    if (j.isdigit()):
                        hubs += text2[i+2][0:text2[i+2].index(j)-1]
                        raiting = text2[i+2][text2[i+2].index(j):-1]
                        subscribers = text2[i+3]
            description = text2[i-1]
            name = text2[i-2]
            print(f"\n\n\n{name}\n{description}\n{hubs}\n{raiting}\n{subscribers}\n\n\n")
            text2.pop(i)
            text2.pop(i+1)
            text2.pop(i+2)
            if not ((text2[i+1].isnumeric() and (text2[i+2].__contains__("K") or text2[i+2].isnumeric())) and (text2[i+2].isnumeric() and (text2[i+3].__contains__("K") or text2[i+3].isnumeric()))):
                text2.pop(i+3)
            text2.pop(i-1)
            text2.pop(i-2)                    
            all_names.append(name)
            all_descriptions.append(description)
            all_hubs.append(hubs)
            all_ratings.append(raiting)
            all_subscribers.append(subscribers)
pars_pdf(extract_text_from_pdf(r"PDF2\Компании _ Хабр.pdf"))
pars_pdf(extract_text_from_pdf(r"PDF2\Компании.pdf"))

['', 'Все потоки', 'Добавить компанию', 'RUVDS.com', 'VDS/VPS-хостинг. Скидка 15% по коду HABR15', 'Пишет в хабы:  Читальный зал,\u2004DIY или Сделай сам,\u2004Научно-популярное,\u2004Электроника для начинающих,\u2004', 'Системное администрирование', '2394.92', '72K', 'Selectel', 'IT-инфраструктура для бизнеса', 'Пишет в хабы:  Компьютерное железо,\u2004Гаджеты,\u2004IT-инфраструктура,\u2004IT-компании,\u2004', 'Производство и разработка электроники', '1935.27', '40K', 'Timeweb Cloud', 'Облачная платформа для разработчиков и бизнеса', 'Пишет в хабы:  Читальный зал,\u2004Научно-популярное,\u2004JavaScript,\u2004DIY или Сделай сам,\u2004История IT', '1538.54', '1.1K', 'OTUS', 'Цифровые навыки от ведущих экспертов', 'Пишет в хабы:  Программирование,\u2004Java,\u2004Машинное обучение,\u2004Тестирование веб-сервисов,\u2004Python', '830.05', '103K', 'Яндекс', 'Как мы делаем Яндекс', 'Пишет в хабы:  Машинное обучение,\u2004Open source,\u2004Высокая производительность,\u2004Программирование,\u2004', 'Интерфейсы', '721.54', '164K', 'Open Data Science', 'Крупнейшее русскоязычное Data Science сообщество', 'Пишет в хабы:  Машинное обучение,\u2004Искусственный интеллект,\u2004Natural Language Processing,\u2004Open source,\u2004', 'Big Data', 'СТАТЬИ +63', 'НОВОСТИ +51', 'ХАБЫ', 'АВТОРЫ', 'КОМПАНИИ', 'Поиск', 'Название ', 'Рейтинг ', 'Подписчики', 'КАК СТАТЬ АВТОРОМ', 'Исследуем Духов Машин в новом Сезоне на Хабре', '', '610.1', '9.6K', 'ГК ЛАНИТ', 'Ведущая многопрофильная группа ИТ-компаний в РФ', 'Пишет в хабы:  Управление проектами,\u2004Карьера в IT-индустрии,\u2004Управление персоналом,\u2004', 'Машинное обучение,\u2004Программирование', '569.92', '54K', 'VK', 'Технологии, которые объединяют', 'Пишет в хабы:  Big Data,\u2004Машинное обучение,\u2004DevOps,\u2004Tarantool,\u2004Облачные сервисы', '536.94', '167K', 'getmatch', 'Рассказываем о том, как строить карьеру в IT', 'Пишет в хабы:  Карьера в IT-индустрии,\u2004Лайфхаки для гиков,\u2004Читальный зал,\u2004IT-эмиграция,\u2004Урбанизм', '436.91', '953', 'Wiren Board', 'Оборудование для автоматизации и мониторинга', 'Пишет в хабы:  Умный дом,\u2004Интернет вещей,\u2004Инженерные системы,\u2004DIY или Сделай сам,\u2004', 'Компьютерное железо', '411.66', '353', 'FirstVDS', 'Виртуальные и выделенные серверы в ДЦ в Москве', 'Пишет в хабы:  Научно-популярное,\u2004Системное администрирование,\u2004Читальный зал,\u2004', 'Информационная безопасность,\u2004IT-инфраструктура', '398.02', '24K', 'Конференции Олега Бунина (Онтико)', 'Профессиональные конференции для IT-разработчиков', 'Пишет в хабы:  Управление разработкой,\u2004Конференции,\u2004DevOps,\u2004Управление проектами,\u2004', 'Карьера в IT-индустрии', '360.51', '58K', 'AGIMA', 'Крупнейший интегратор digital-решений', 'Пишет в хабы:  Карьера в IT-индустрии,\u2004Управление проектами,\u2004Конференции,\u2004Управление персоналом,\u2004', 'Управление продуктом', '336.45', '519', 'Альфа-Банк', 'Лучший мобильный банк по версии Markswebb', 'Пишет в хабы:  Конференции,\u2004Анализ и проектирование систем,\u2004Машинное обучение,\u2004JavaScript,\u2004', 'Карьера в IT-индустрии', '', '311.59', '24K', 'Postgres Professional', 'Разработчик СУБД Postgres Pro', 'Пишет в хабы:  PostgreSQL,\u2004SQL,\u2004Администрирование баз данных,\u2004Open source,\u2004Хранение данных', '305.42', '76K', 'Ozon Tech', 'Стремимся делать лучший e-commerce в России', 'Пишет в хабы:  Конференции,\u2004Высокая производительность,\u2004Go,\u2004Тестирование веб-сервисов,\u2004', 'Программирование', '282.75', '28K', 'TINKOFF', 'IT’s Tinkoff — просто о сложном', 'Пишет в хабы:  Разработка под Android,\u2004Машинное обучение,\u2004Тестирование IT-систем,\u2004', 'Разработка мобильных приложений,\u2004Open source', '282.47', '40K', 'Хабр Карьера', 'Помогаем строить карьеру в IT', 'Пишет в хабы:  Карьера в IT-индустрии,\u2004Управление персоналом,\u2004Исследования и прогнозы в IT,\u2004', 'Блог компании Хабр,\u2004Финансы в IT', '280.35', '14K', 'JUG Ru Group', 'Конференции для Senior-разработчиков', 'Пишет в хабы:  Конференции,\u2004Java,\u2004Тестирование IT-систем,\u2004Разработка мобильных приложений,\u2004JavaScript', '276.72', '41K', 'Southbridge', 'Обеспечиваем стабильную работу highload-проектов', 'Пишет в хабы:  IT-инфраструктура,\u2004DevOps,\u2004Системное администрирование,\u2004Карьера в IT-индустрии,\u2004', 'Программирование', '273.3', '47K', '1', '2', '3', '... 16', '17', 'ФИЛЬТР', 'Все', '323', 'Веб-разработка', '98', 'Программное обеспечение', '180', '', 'Аппаратное обеспечение', '40', 'Дизайн и юзабилити', '22', 'Реклама и маркетинг', '9', 'СМИ', '5', 'Консалтинг и поддержка', '49', 'Рекрутинг и HR', '9', 'Электронная коммерция', '41', 'Некоммерческие организации', '5', 'Оптимизация', '9', 'Производство мультимедиа-контента', '9', 'Связь и телекоммуникации', '54', 'Домены и хостинг', '17', 'Поисковые технологии', '9', 'Мобильные технологии', '72', 'Веб-сервисы', '97', 'Игры и развлечения', '11', 'Информационная безопасность', '47', 'Ваш аккаунт', 'Войти', 'Регистрация', 'Разделы', 'Публикации', 'Новости', 'Хабы', 'Компании', 'Авторы', 'Песочница', 'Информация', 'Устройство сайта', 'Для авторов', 'Для компаний', 'Документы', 'Соглашение', 'Конфиденциальность', 'Услуги', 'Корпоративный блог', 'Медийная реклама', 'Нативные проекты', 'Образовательные', 'программы', 'Стартапам', 'Мегапроекты', '', 'Настройка языка', 'Техническая поддержка', 'Вернуться на старую версию', '© 2006–2023, Habr', '']



Southbridge
Обеспечиваем стабильную работу highload-проектов
Пишет в хабы:  IT-инфраструктура, DevOps, Системное администрирование, Карьера в IT-индустрии, Программирование
273.3
47K






JUG Ru Group
Конференции для Senior-разработчиков
Пишет в хабы:  Конференции, Java, Тестирование IT-систем, Разработка мобильных приложений, JavaScript
276.72
41K






Хабр Карьера
Помогаем строить карьеру в IT
Пишет в хабы:  Карьера в IT-индустрии, Управление персоналом, Исследования и прогнозы в IT, Блог компании Хабр, Финансы в IT
280.35
14K






TINKOFF
IT’s Tinkoff — просто о сложном
Пишет в хабы:  Разработка под Android, Машинное обучение, Тестирование IT-систем, Разработка мобильных приложений, Open source
282.47
40K






Ozon Tech
Стремимся делать лучший e-commerce в России
Пишет в хабы:  Конференции, Высокая производительность, Go, Тестирование веб-сервисов, Программирование
282.75
28K






Postgres Professional
Разработчик СУБД Postgres Pro
Пишет в хабы:  PostgreSQL, SQL, Администрирование баз данных, Open source, Хранение данных
305.42
76K






Альфа-Банк
Лучший мобильный банк по версии Markswebb
Пишет в хабы:  Конференции, Анализ и проектирование систем, Машинное обучение, JavaScript, Карьера в IT-индустрии
311.59
24K






AGIMA
Крупнейший интегратор digital-решений
Пишет в хабы:  Карьера в IT-индустрии, Управление проектами, Конференции, Управление персоналом, Управление продуктом
336.45
519






Конференции Олега Бунина (Онтико)
Профессиональные конференции для IT-разработчиков
Пишет в хабы:  Управление разработкой, Конференции, DevOps, Управление проектами, Карьера в IT-индустрии
360.51
58K






FirstVDS
Виртуальные и выделенные серверы в ДЦ в Москве
Пишет в хабы:  Научно-популярное, Системное администрирование, Читальный зал, Информационная безопасность, IT-инфраструктура
398.02
24K






Wiren Board
Оборудование для автоматизации и мониторинга
Пишет в хабы:  Умный дом, Интернет вещей, Инженерные системы, DIY или Сделай сам, Компьютерное железо
411.66
353






getmatch
Рассказываем о том, как строить карьеру в IT
Пишет в хабы:  Карьера в IT-индустрии, Лайфхаки для гиков, Читальный зал, IT-эмиграция, Урбанизм
436.91
953






VK
Технологии, которые объединяют
Пишет в хабы:  Big Data, Машинное обучение, DevOps, Tarantool, Облачные сервисы
536.94
167K






ГК ЛАНИТ
Ведущая многопрофильная группа ИТ-компаний в РФ
Пишет в хабы:  Управление проектами, Карьера в IT-индустрии, Управление персоналом, Машинное обучение, Программирование
569.92
54K






Open Data Science
Крупнейшее русскоязычное Data Science сообщество
Пишет в хабы:  Машинное обучение, Искусственный интеллект, Natural Language Processing, Open source, Big Data
610.1
9.6K






Яндекс
Как мы делаем Яндекс
Пишет в хабы:  Машинное обучение, Open source, Высокая производительность, Программирование, Интерфейсы
721.54
164K






OTUS
Цифровые навыки от ведущих экспертов
Пишет в хабы:  Программирование, Java, Машинное обучение, Тестирование веб-сервисов, Python
830.05
103K






Timeweb Cloud
Облачная платформа для разработчиков и бизнеса
Пишет в хабы:  Читальный зал, Научно-популярное, JavaScript, DIY или Сделай сам, История IT
1538.54
1.1K






Selectel
IT-инфраструктура для бизнеса
Пишет в хабы:  Компьютерное железо, Гаджеты, IT-инфраструктура, IT-компании, Производство и разработка электроники
1935.27
40K






RUVDS.com
VDS/VPS-хостинг. Скидка 15% по коду HABR15
Пишет в хабы:  Читальный зал, DIY или Сделай сам, Научно-популярное, Электроника для начинающих, Системное администрирование
2394.92
72K



['', 'RUVDS.com', 'VDS/VPS-хостинг. Скидка 15% по коду HABR15', 'Пишет в хабы:  Читальный зал,\x00DIY или Сделай сам,\x00Научно-популярное,\x00Электроника для начинающих,\x00Системное администрирование', '2393.91', '72K', 'Selectel', 'IT-инфраструктура для бизнеса', 'Пишет в хабы:  Компьютерное железо,\x00Гаджеты,\x00IT-инфраструктура,\x00IT-компании,\x00Производство и разработка электроники', '1935.27', '40K', 'Timeweb Cloud', 'Облачная платформа для разработчиков и бизнеса', 'Пишет в хабы:  Читальный зал,\x00Научно-популярное,\x00JavaScript,\x00DIY или Сделай сам,\x00История IT', '1542.55', '1.1K', 'OTUS', 'Цифровые навыки от ведущих экспертов', 'Пишет в хабы:  Программирование,\x00Java,\x00Машинное обучение,\x00Тестирование веб-сервисов,\x00Python', '832.56', '103K', 'Яндекс', 'Как мы делаем Яндекс', 'Добавить компанию', 'Все потоки', 'СТАТЬИ', '+64', 'НОВОСТИ', '+50', 'ХАБЫ', 'АВТОРЫ', 'КОМПАНИИ', 'Название ', 'Рейтинг ', 'Подписчики', 'КАК СТАТЬ АВТОРОМ', '', 'Пишет в хабы:  Машинное обучение,\x00Open source,\x00Высокая производительность,\x00Программирование,\x00Интерфейсы', '721.53', '164K', 'Open Data Science', 'Крупнейшее русскоязычное Data Science сообщество', 'Пишет в хабы:  Машинное обучение,\x00Искусственный интеллект,\x00Natural Language Processing,\x00Open source,\x00Big Data', '612.13', '9.6K', 'ГК ЛАНИТ', 'Ведущая многопрофильная группа ИТ-компаний в РФ', 'Пишет в хабы:  Управление проектами,\x00Карьера в IT-индустрии,\x00Управление персоналом,\x00Машинное обучение,\x00Программирование', '569.92', '54K', 'VK', 'Технологии, которые объединяют', 'Пишет в хабы:  Big Data,\x00Машинное обучение,\x00DevOps,\x00Tarantool,\x00Облачные сервисы', '536.95', '167K', 'getmatch', 'Рассказываем о том, как строить карьеру в IT', 'Пишет в хабы:  Карьера в IT-индустрии,\x00Лайфхаки для гиков,\x00Читальный зал,\x00IT-эмиграция,\x00Урбанизм', '436.91', '953', 'Wiren Board', 'Оборудование для автоматизации и мониторинга', 'Пишет в хабы:  Умный дом,\x00Интернет вещей,\x00Инженерные системы,\x00DIY или Сделай сам,\x00Компьютерное железо', '411.66', '353', 'FirstVDS', 'Виртуальные и выделенные серверы в ДЦ в Москве', 'Пишет в хабы:  Научно-популярное,\x00Системное администрирование,\x00Читальный зал,\x00Информационная безопасность,\x00IT-инфраструктура', '398.02', '24K', '', 'Конференции Олега Бунина (Онтико)', 'Профессиональные конференции для IT-разработчиков', 'Пишет в хабы:  Управление разработкой,\x00Конференции,\x00DevOps,\x00Управление проектами,\x00Карьера в IT-индустрии', '360.51', '58K', 'AGIMA', 'Крупнейший интегратор digital-решений', 'Пишет в хабы:  Карьера в IT-индустрии,\x00Управление проектами,\x00Конференции,\x00Управление персоналом,\x00Управление продуктом', '336.45', '519', 'Альфа-Банк', 'Лучший мобильный банк по версии Markswebb', 'Пишет в хабы:  Конференции,\x00Анализ и проектирование систем,\x00Машинное обучение,\x00JavaScript,\x00Карьера в IT-индустрии', '311.6', '24K', 'Postgres Professional', 'Разработчик СУБД Postgres Pro', 'Пишет в хабы:  PostgreSQL,\x00SQL,\x00Администрирование баз данных,\x00Open source,\x00Хранение данных', '305.42', '76K', 'Ozon Tech', 'Стремимся делать лучший e-commerce в России', 'Пишет в хабы:  Конференции,\x00Высокая производительность,\x00Go,\x00Тестирование веб-сервисов,\x00Программирование', '282.75', '28K', 'TINKOFF', 'IT’s Tinkoff — просто о сложном', 'Пишет в хабы:  Разработка под Android,\x00Машинное обучение,\x00Тестирование IT-систем,\x00Разработка мобильных приложений,\x00Open source', '282.47', '40K', 'Хабр Карьера', 'Помогаем строить карьеру в IT', 'Пишет в хабы:  Карьера в IT-индустрии,\x00Управление персоналом,\x00Исследования и прогнозы в IT,\x00Блог компании Хабр,\x00Финансы в IT', '280.33', '14K', '', 'JUG Ru Group', 'Конференции для Senior-разработчиков', 'Пишет в хабы:  Конференции,\x00Java,\x00Тестирование IT-систем,\x00Разработка мобильных приложений,\x00JavaScript', '276.72', '41K', 'Southbridge', 'Обеспечиваем стабильную работу highload-проектов', 'Пишет в хабы:  IT-инфраструктура,\x00DevOps,\x00Системное администрирование,\x00Карьера в IT-индустрии,\x00Программирование', '272.35', '47K', '1', '2', '3', '..', '', 'Ваш', 'аккаунт', 'Разделы', 'Информация', 'Услуги', 'ФИЛЬТР', 'Все', '323', 'Web-development', '98', 'Software', '180', 'Hardware', '40', 'Design and usability', '22', 'Advertisement and marketing', '9', 'Mass media', '5', 'Consulting and support', '49', 'HR', '9', 'E-commerce', '41', 'Non-profit organizations', '5', 'Optimization', '9', 'Producing multimedia content', '9', 'Telecommunications', '54', 'Domains and hosting', '17', 'Search Engines', '9', 'Mobile technologies', '72', 'Web-services', '97', 'Games and entertainment', '11', 'Information Security', '47', '', 'Войти', 'Регистрация', 'Публикации', 'Новости', 'Хабы', 'Компании', 'Авторы', 'Песочница', 'Устройство сайта', 'Для авторов', 'Для компаний', 'Документы', 'Соглашение', 'Конфиденциальность', 'Корпоративный блог', 'Медийная реклама', 'Нативные проекты', 'Образовательные', 'программы', 'Стартапам', 'Мегапроекты', 'Настройка языка', 'Техническая поддержка', 'Вернуться на старую версию', '© 2006–2023, Habr', '']



Southbridge
Обеспечиваем стабильную работу highload-проектов
Пишет в хабы:  IT-инфраструктура, DevOps, Системное администрирование, Карьера в IT-индустрии, Программирование
272.35
47K






JUG Ru Group
Конференции для Senior-разработчиков
Пишет в хабы:  Конференции, Java, Тестирование IT-систем, Разработка мобильных приложений, JavaScript
276.72
41K






Хабр Карьера
Помогаем строить карьеру в IT
Пишет в хабы:  Карьера в IT-индустрии, Управление персоналом, Исследования и прогнозы в IT, Блог компании Хабр, Финансы в IT
280.33
14K






TINKOFF
IT’s Tinkoff — просто о сложном
Пишет в хабы:  Разработка под Android, Машинное обучение, Тестирование IT-систем, Разработка мобильных приложений, Open source
282.47
40K






Ozon Tech
Стремимся делать лучший e-commerce в России
Пишет в хабы:  Конференции, Высокая производительность, Go, Тестирование веб-сервисов, Программирование
282.75
28K






Postgres Professional
Разработчик СУБД Postgres Pro
Пишет в хабы:  PostgreSQL, SQL, Администрирование баз данных, Open source, Хранение данных
305.42
76K






Альфа-Банк
Лучший мобильный банк по версии Markswebb
Пишет в хабы:  Конференции, Анализ и проектирование систем, Машинное обучение, JavaScript, Карьера в IT-индустрии
311.6
24K






AGIMA
Крупнейший интегратор digital-решений
Пишет в хабы:  Карьера в IT-индустрии, Управление проектами, Конференции, Управление персоналом, Управление продуктом
336.45
519






Конференции Олега Бунина (Онтико)
Профессиональные конференции для IT-разработчиков
Пишет в хабы:  Управление разработкой, Конференции, DevOps, Управление проектами, Карьера в IT-индустрии
360.51
58K






FirstVDS
Виртуальные и выделенные серверы в ДЦ в Москве
Пишет в хабы:  Научно-популярное, Системное администрирование, Читальный зал, Информационная безопасность, IT-инфраструктура
398.02
24K






Wiren Board
Оборудование для автоматизации и мониторинга
Пишет в хабы:  Умный дом, Интернет вещей, Инженерные системы, DIY или Сделай сам, Компьютерное железо
411.66
353






getmatch
Рассказываем о том, как строить карьеру в IT
Пишет в хабы:  Карьера в IT-индустрии, Лайфхаки для гиков, Читальный зал, IT-эмиграция, Урбанизм
436.91
953






VK
Технологии, которые объединяют
Пишет в хабы:  Big Data, Машинное обучение, DevOps, Tarantool, Облачные сервисы
536.95
167K






ГК ЛАНИТ
Ведущая многопрофильная группа ИТ-компаний в РФ
Пишет в хабы:  Управление проектами, Карьера в IT-индустрии, Управление персоналом, Машинное обучение, Программирование
569.92
54K






Open Data Science
Крупнейшее русскоязычное Data Science сообщество
Пишет в хабы:  Машинное обучение, Искусственный интеллект, Natural Language Processing, Open source, Big Data
612.13
9.6K






Яндекс
Как мы делаем Яндекс
Пишет в хабы:  Машинное обучение, Open source, Высокая производительность, Программирование, Интерфейсы
721.53
164K






OTUS
Цифровые навыки от ведущих экспертов
Пишет в хабы:  Программирование, Java, Машинное обучение, Тестирование веб-сервисов, Python
832.56
103K






Timeweb Cloud
Облачная платформа для разработчиков и бизнеса
Пишет в хабы:  Читальный зал, Научно-популярное, JavaScript, DIY или Сделай сам, История IT
1542.55
1.1K






Selectel
IT-инфраструктура для бизнеса
Пишет в хабы:  Компьютерное железо, Гаджеты, IT-инфраструктура, IT-компании, Производство и разработка электроники
1935.27
40K






RUVDS.com
VDS/VPS-хостинг. Скидка 15% по коду HABR15
Пишет в хабы:  Читальный зал, DIY или Сделай сам, Научно-популярное, Электроника для начинающих, Системное администрирование
2393.91
72K

In [23]:
df = pd.DataFrame({
'NameCompany': all_names,
'Rating': all_ratings,
'Description': all_descriptions,
'Hub': all_hubs,
'Subscribers': all_subscribers,
})

In [25]:
df.head()

,NameCompany,Rating,Description,Hub,Subscribers
0,Southbridge,273.3,Обеспечиваем стабильную работу highload-проектов,"Пишет в хабы: IT-инфраструктура, DevOps, Сист...",47K
1,JUG Ru Group,276.72,Конференции для Senior-разработчиков,"Пишет в хабы: Конференции, Java, Тестирование...",41K
2,Хабр Карьера,280.35,Помогаем строить карьеру в IT,"Пишет в хабы: Карьера в IT-индустрии, Управле...",14K
3,TINKOFF,282.47,IT’s Tinkoff — просто о сложном,"Пишет в хабы: Разработка под Android, Машинно...",40K
4,Ozon Tech,282.75,Стремимся делать лучший e-commerce в России,"Пишет в хабы: Конференции, Высокая производит...",28K

In [26]:
df.to_csv("dataset.csv", index=False)

In [27]:
df2 = pd.read_csv("dataset.csv")
df2.head()

,NameCompany,Rating,Description,Hub,Subscribers
0,Southbridge,273.30,Обеспечиваем стабильную работу highload-проектов,"Пишет в хабы: IT-инфраструктура, DevOps, Сист...",47K
1,JUG Ru Group,276.72,Конференции для Senior-разработчиков,"Пишет в хабы: Конференции, Java, Тестирование...",41K
2,Хабр Карьера,280.35,Помогаем строить карьеру в IT,"Пишет в хабы: Карьера в IT-индустрии, Управле...",14K
3,TINKOFF,282.47,IT’s Tinkoff — просто о сложном,"Пишет в хабы: Разработка под Android, Машинно...",40K
4,Ozon Tech,282.75,Стремимся делать лучший e-commerce в России,"Пишет в хабы: Конференции, Высокая производит...",28K